### ISSUE TITLE
Provide an example of how to test with the in memory store

### ISSUE THREAD

**Issue by tcoopman** [commanded/commanded#100]
I was wondering how you combine the in memory store with an other event store, in case you want to use the in memory store for testing.

The problem is that the `:eventstore` is an extra_application that get's started, but in testing I only want the memory store, so now I solve this by doing this in `mix.exs`:

```elixir
  def application do
    extra_applications = if Mix.env == :test, 
      do: [:logger, :runtime_tools],
      else: [:logger, :runtime_tools, :eventstore]

    [
      mod: {MotivateMe.Application, []},
      extra_applications: extra_applications
    ]
  end
```

But that doesn't seem like the best way of solving this. Also, maybe at some point I do want to have some integration tests that run against the database, so I was wondering if it was possible to choose in a test against what implementation of the eventstore the test should run?

**Comment by slashdotdash** [comment]
Including `:evenstore` in extra applications using the Mix environment, as you have, is a reasonable approach. An alternative is to configure its `runtime` setting based on the environment:

```elixir
defp deps do
  [
    {:eventstore, "~> 0.11", runtime: Mix.env != :test},
  ]
end
```

To change the configured event store for an individual test, or suite of tests, you would need to reconfigure the event store adapter for Commanded:

```elixir
def use_in_memory_event_store do
  :ok = Application.stop(:commanded)

  Application.put_env(:commanded,  :event_store_adapter, Commanded.EventStore.Adapters.InMemory)
  
  {:ok, _event_store} = Commanded.EventStore.Adapters.InMemory.start_link()

  {:ok, _} = Application.ensure_all_started(:commanded)
end
```

```elixir
def use_in_postgres_event_store do
  :ok = Application.stop(:commanded)

  Application.put_env(:commanded,  :event_store_adapter, Commanded.EventStore.Adapters.EventStore)
  
  {:ok, _event_store} = Commanded.EventStore.Adapters.InMemory.start_link()
 
  {:ok, _} = Application.ensure_all_started(:eventstore)
  {:ok, _} = Application.ensure_all_started(:commanded)
end
```

You could provide an ExUnit case template to configure either in-memory or Postgres event store by calling the above functions in its `setup/0`.

**Comment by slashdotdash** [comment]
Documented in the Wiki as [In-memory event store](https://github.com/commanded/commanded/wiki/In-memory-event-store).
