### ISSUE TITLE
How do we handle deletes?

### ISSUE THREAD

**Issue by saimonmoore** [commanded/commanded#118]
This is a very noob question but I've not seen it addressed in either the docs, the tests or the example code.

I have a `DeleteTeam`/`TeamDeleted` command/event and in my Team aggregate `#apply` method I am just returning nil because the state is going away but `commanded` is complaining.

In the example code I've seen, I noticed that they are just marking items as deleted (via a flag) and updating the state. Is this what the recommended approach is? What if I really want to delete the state?

**Comment by saimonmoore** [comment]
Hmmm it appears to have auto fixed itself ja ja..but in any case just wondering what the best practice is in this case...

**Comment by slashdotdash** [comment]
Hey @saimonmoore, 

I would recommend using an "is deleted" flag or set a status field to deleted in your aggregate's state in the `apply/2` function:

```elixir
def apply(%Team{} = team, %TeamDeleted{}) do
  %Team{team | status: :deleted}
end
```

This ensures that any further commands sent to the aggregate can be prevented:

```elixir
def execute(%Team{status: :deleted}, %DeleteTeam{}) do
  {:error, :already_deleted}
end
```

You can use the [Aggregate lifespan](https://github.com/commanded/commanded/blob/master/guides/Commands.md#aggregate-lifespan) feature to actually stop the aggregate process once it has been deleted:

```elixir
defmodule TeamLifespan do
  @behaviour Commanded.Aggregates.AggregateLifespan

  def after_command(%DeleteTeam{}) do: 0
  def after_command(_), do: :infinity
end
```

The aggregate's current state is only held in memory, so once the process is stopped the state is gone. 

Hope that helps.

**Comment by saimonmoore** [comment]
Cool. Yeah that makes sense. I suspected this was a better approach. Thanks @slashdotdash .

**Comment by Calamari** [comment]
Hey ho. 

First: I like that library you build here. It's a really good way to figure out how CQRS works in praxis.

About this, how about putting this into the wiki as FAQ or something? Because I have the same question and just found this explanation by accident. I think it is very good to know.

Keep up the good work. Thanks.
