### ISSUE TITLE
Reset event handler

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#120]
Allow an event handler to be reset by restarting its event store subscription from its `start_from` config. This should allow an individual handler to restart while the app is running. An example use would be to rebuild a read model projection from scratch.

A mix task should be provided to restart a handler by name:`mix commanded.reset <handler name>`

The `Commanded.Event.Handler` behaviour should allow an optional reset callback function for handler specific behaviour (e.g. read model projection reset its own last seen event pointer). 

```elixir
defmodule ExampleHandler do
  use Commanded.Event.Handler, 
    name: "ExampleHandler",
    start_from: :origin

  def before_reset do
    # executed before the event handler's subscription is reset to origin and process is restarted
    :ok
  end
  
  def handle(%AnEvent{..}, _metadata) do
    :ok
  end
end
```

**Comment by ilgarm** [comment]
@slashdotdash (thanks for the great library, btw) do you plan to work on this feature?

**Comment by slashdotdash** [comment]
Sorry @ilgarm it's not currently a priority for me to work on. Is it a feature you'd like to see implemented?

**Comment by ilgarm** [comment]
@slashdotdash thanks for prompt reply. Yes, I am interested in this functionality, and moreover, imo, would be great to have it similar to aggregates snapshot functionality. I mean, resetting snapshot version to reset event handler. Or having both respective mix tasks, maybe.

Also, somehow related to this context: I could not find an easy option to provide additional configuration to projectors. I would like to implement Elasticserarch projector, f.e., and needed to pass some additional params, like index name, etc. Not much documentation describing that. So, I had a look at ecto projectors source code, and seems no easy way to do that without writing macros. Please, correct me if I am wrong.

Thank you!

**Comment by Calamari** [comment]
I would love to see this feature since I am struggling to rebuild my read models after changing the projections.

**Comment by Freyskeyd** [comment]
I'm closing this issue @Calamari @slashdotdash @ilgarm due to #293 

Feel free to add comments if I missed something!
