### ISSUE TITLE
Allow `command_uuid` to be provided during command dispatch

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#134]
Each dispatched command is assigned a unique `command_uuid`. This is used by the Commanded audit middleware to record the command dispatch success/failure. It’s also used to generate the causation id for alll events created by the command.

Currently  `command_uuid` is [generated as a UUID for each command dispatch in the router](https://github.com/commanded/commanded/blob/767bba14c41c13eae6ea7f8ec1387ccd938dbbc9/lib/commanded/commands/router.ex#L380). The proposal is to allow it to be set during command dispatch:

```elixir
command_uuid = UUID.uuid4()  # .. or from external request
:ok = MyRouter.dispatch(%ExampleCommand{…}, command_uuid: command_uuid)
```

By allowing the `command_uuid` to be set from a user's request you can implement command de-duplication, as a [middleware](https://github.com/commanded/commanded/blob/767bba14c41c13eae6ea7f8ec1387ccd938dbbc9/guides/Commands.md#middleware), to ensure you don't process the same request more than once.

**Comment by prsn-uk** [comment]
It is probably a good idea to change the name to `command_id` to change expectations about what can be assigned.

**Comment by slashdotdash** [comment]
Having thought about the issue further it may be better to leave `command_uuid` unchanged but instead include an idempotency key in the metadata passed to command dispatch. This would allow any string to be used:

```elixir
:ok = MyRouter.dispatch(%ExampleCommand{…}, metadata: %{
  "idempotency_key" => "HCgri8WjBm3I89Q4"
})
```

Middleware has access to metadata during dispatch to use for de-duplication purposes.

This approach will work now, with no changes required. What are your thoughts @prsn-uk?

**Comment by prsn-uk** [comment]
This is my current approach - the idempotency key being what I call `command_id` (which is a uuid set by the end user) + their `user_id`.

In my system this also has the added purpose of letting the end user associate business level validation errors with One-Way Commands when an async notification is sent to them.

I agree that your solution is the best and will cause the least disruption.

**Comment by slashdotdash** [comment]
Closing this issue as it's already possible to acheive using the alternative approach I've described above, with no changes necessary.
