### ISSUE TITLE
hexdocs.pm using documentation from master while claiming to be 0.15.1

### ISSUE THREAD

**Issue by prsn-uk** [commanded/commanded#136]
`Commanded.Commands.CompositeRouter` does not existing in the latest hex.pm version (0.15.1) but is appearing in the hexdocs.pm docs under that version.

https://github.com/commanded/commanded/tree/v0.15.1/lib/commanded/commands
https://hexdocs.pm/commanded/0.15.1/Commanded.Commands.CompositeRouter.html

**Comment by ericmj** [comment]
Docs can be republished by checking out the v0.15.1 tag and running `mix hex.publish docs` again.

**Comment by slashdotdash** [comment]
Thanks @prsn-uk, I've republished the Hex docs from the v0.15.1 tag as per @ericmj suggestion.
