### ISSUE TITLE
given when then

### ISSUE THREAD

**Issue by tcoopman** [commanded/commanded#142]
I would like to write some of my tests in the form of

```
Given [events]
When command
Then [events]
```

So I would like to initialize my aggregates with some events, then dispatch a command and see what the result is.

Is something like this possible? I know it's possible to just test the aggregate directly without using the router, but is it also possible to put some events into the store so that dispatching via the router works?

**Comment by slashdotdash** [comment]
Yes you can use that approach for testing. Use `Commanded.EventStore.append_to_stream/3` to append events to whatever event store you've configured to use with Commanded.

You'll need to map your app's domain events to `Commanded.EventStore.EventData` structs as follows:

```elixir
event_data =
  Enum.map(events, fn -> event
    %Commanded.EventStore.EventData{
      causation_id: UUID.uuid4(),
      correlation_id: UUID.uuid4(),
      event_type: Commanded.EventStore.TypeProvider.to_string(event),
      data: event,
      metadata: %{},
    }
  )

{:ok, _} = Commanded.EventStore.append_to_stream(stream_uuid, expected_version, event_data)
```

The `stream_uuid` will be your aggregate's identity and `expected_version` is the aggregate version (count of events already appended to its stream).

Once you've appended the events you can dispatch the command via your router. The aggregate process will be started, it'll fetch its events, including those you just appended, and then handle the command.

**Comment by tcoopman** [comment]
Thanks this works perfectly!
