### ISSUE TITLE
does causation / correlation actually work?

### ISSUE THREAD

**Issue by Trevoke** [commanded/commanded#144]
Test: 

```elixir
    test "related events are connected", %{consumer: consumer} do
      # trigger Event.RegisteredConsumer 
      assert_receive_event(Account.Event.RegisteredConsumer, fn(event, md1) ->
        assert_receive_event(Financial.Event.ConsumerInitialized, fn(fin_init, md2) ->
          assert fin_init.consumer_id == event.consumer_id
          assert md2.correlation_id == md1.correlation_id
          assert md2.causation_id == md1.event_id
        end)
      end)
    end
```

Relevant code snippets: 

```elixir
defmodule EventHandler.AccountToFinancial do
  use Commanded.Event.Handler,
    name: "AccountToFinancial",
    consistency: :eventual

  def handle(%Event.RegisteredConsumer{consumer_id: uuid},
    %{event_id: causation_id, correlation_id: correlation_id} = _metadata) do
    Financial.initialize_consumer(
      %{consumer_id: uuid},
      causation_id: causation_id, correlation_id: correlation_id
    )
    :ok
  end
end

defmodule Financial do
  def initialize_consumer(%{consumer_id: _id} = attrs, metadata \\ []) do
    init_consumer =
      attrs
      |> assign(:datetime, Timex.now(:utc))
      |> Command.InitializeConsumer.new
    case Router.dispatch(init_consumer, metadata) do
      :ok -> {:ok, init_consumer}
      reply -> reply
    end
  end
```

I made a small modification in the assertions code of commanded:

```elixir
  defp do_assert_receive(subscription, event_type, predicate_fn, assertion_fn) do
    assert_receive {:events, received_events}, default_receive_timeout()

    ack_events(subscription, received_events)

    expected_type = Atom.to_string(event_type)
    expected_event = Enum.find(received_events, fn received_event ->
      with ^expected_type <- received_event.event_type,
           true <- apply(predicate_fn, [received_event.data]) do
        received_event
      else
        _ -> false
      end
    end)

    IO.inspect expected_event

    case expected_event do
      nil -> do_assert_receive(subscription, event_type, predicate_fn, assertion_fn)
      received_event ->
        if is_function(assertion_fn, 1) do
          apply(assertion_fn, [received_event.data])
        else
          apply(assertion_fn, [received_event.data, received_event |> Map.from_struct |> Map.delete(:data)])
        end
    end
  end
```

And this fails..

```
     code:  assert md2.causation_id() == md1.event_id()
     left:  "2cde274c-d2f6-4c44-9273-ae77268429e6"
     right: "d77ddd2b-1105-45d1-bae0-6c60b845743c"
```

Near as I can figure out, I'm following the instructions for connecting causation/correlation ids; what am I missing?

**Comment by slashdotdash** [comment]
The causation id of an event is the command id that created it. This allows you to follow the chain of commands and events.

**Comment by Trevoke** [comment]
You mean that to fully track I would need to track the command as well,
which means that I need the audit middleware?

This might be a little more annoying to test fully than expected.

**Comment by slashdotdash** [comment]
Using [Commanded audit middleware](https://github.com/commanded/commanded-audit-middleware/) would allow you to verify the causation id flow.

Assume you dispatch a command (Command1) - providing a correlation_id, but no causation_id - which creates a single event (Event1). Then an event handler dispatches a command in response (Command2) - copying the relevant cuasation and correlation ids - creating another event (Event2). The flow of correlation and causation ids should be:

- Command1 (causation_id: nil, correlation_id: "correlate1", command_uuid: "command1") 
- Event1 (causation_id: "command1", correlation_id: "correlate1", event_id: "event1")
- Command2 (causation_id: "event1", correlation_id: "correlate1", command_uuid: "command2")
- Event1 (causation_id: "command2", correlation_id: "correlate1", event_id: "event2")

**Comment by Trevoke** [comment]
Gotcha, thank you.

This will be for a future PR. :)
