### ISSUE TITLE
Process manager idle timeout

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#148]
Allow an idle timeout to be specified for process manager processes.

Two possible approaches:

1. Define an `idle_timeout`, in milliseconds, as an option to start link allowing it to be configured when including a process manager in a supervisor:

```elixir
children = [
  {MyApp.FooManager, idle_timeout: 60_000},
]
```

2. Define a lifespan behaviour, similar to aggregate lifespan, to be defined per process manager. It would decide when to shutdown the process depending upon the recently dispatched command, handled event, or error.

**Comment by Freyskeyd** [comment]
I think it's better to have a proper lifespan behaviour like aggregate.
