### ISSUE TITLE
InMemoryEventStoreCase fails if event_store was started in test_helper

### ISSUE THREAD

**Issue by naps62** [commanded/commanded#151]
We've had to do pretty much everything that is suggested [here](https://github.com/commanded/commanded/wiki/In-memory-event-store)

This raised some conflicts between two of the suggestions.

First, of all, we had to start the event_store in our test_helper:

```elixir
{:ok, _pid} = Commanded.EventStore.Adapters.InMemory.start_link()
{:ok, _} = Application.ensure_all_started(:my_app)
```

But we're also using the InMemoryEventStoreCase, because we want to clean up after each test. This raises a problem, because when `setup` runs, the event_store was already started. So the first step was to change this:

```elixir
setup do
    event_store = case = Commanded.EventStore.Adapters.InMemory.start_link() do
      {:ok, pid} -> pid
      {:error, {:already_started, pid}} -> pid
    end

    # ...
  end
```

This way, if the event_store is already running, we ignore the error, and still capture the pid.

This introduces another problem though, because we're later doing `Process.unlink(pid)`. But on the first run, the event_store was actually initiated by the test_helper call, and not the `setup` method. So ti came from a different process.

Since `Process.unlink` unlinks a pid from the current process, this doesn't work. The process remained linked to the original ExUnit process, causing the whole test suite to shutdown.
The solution was to do a similar logic in the test_helper:

```elixir
# test_helper.exs
case Commanded.EventStore.Adapters.InMemory.start_link() do
  {:ok, pid} -> Process.unlink(pid) # unlink the process right away
  _ -> nil
end

{:ok, _} = Application.ensure_all_started(:my_app)
```

This also prevents this from failing under an umbrella app, where multiple apps would try to initiate the InMemory store. Pattern matching to `{:ok, pid}` as the wiki suggests would also fail in that case

Not sure if there was a better way do to this (the code does look ugly). But maybe the documentation of that page should take this into account?

**Comment by slashdotdash** [comment]
Thanks for the feedback, I'll have another go at clarifying the Wiki page.

You don't need to start the in-memory event store in `test_helper.exs` if you use the `InMemoryEventStoreCase`.

Also, you need to run the tests with the `--no-start` flag:

```console
mix test --no-start
```

Finally, in the ExUnit case template you must start your own application after starting the in-memory event store, and also stop it `on_exit`:

```elixir
defmodule InMemoryEventStoreCase do
  use ExUnit.CaseTemplate

  setup do
    {:ok, event_store} = Commanded.EventStore.Adapters.InMemory.start_link()

   Application.ensure_all_started(:my_app)

    on_exit fn ->
      Application.stop(:my_app)

      shutdown(event_store)
    end

    :ok
  end

  def shutdown(pid) when is_pid(pid) do
    Process.unlink(pid)
    Process.exit(pid, :shutdown)

    ref = Process.monitor(pid)
    assert_receive {:DOWN, ^ref, _, _, _}, 5_000
  end
end
```

**Comment by slashdotdash** [comment]
I've updated the [In-memory event store](https://github.com/commanded/commanded/wiki/In-memory-event-store) Wiki page. It's hopefully added some further clarity.

**Comment by naps62** [comment]
Ok so this part is probably where I'm confused now:

> Finally, in the ExUnit case template you must start your own application after starting the in-memory event store, and also stop it on_exit

We considered that option, but it doesn't seem to make a lot of sense. If there are other tests in the codebase that do not rely on InMemoryEventStore, they would still need to call `ensure_all_started`, so we'd have to add a `setup` call to all of them. Am I correct?

**Comment by naps62** [comment]
Oh, and adding to the fact that we also need to stop it `on_exit`, isn't that a huge overhead for the setup/teardown of each test?

**Comment by naps62** [comment]
@slashdotdash I was thinking about this a bit more. Wouldn't it be possible to have a call on the InMemory GenServer that would just reset it's state to the initial one?

So, from a quick glance at the codebase, it would be something like this:

```elixir
defmodule Commanded.EventStore.Adapters.InMemory do
  def handle_call(:reset, _from, old_state) do
    new_state =  %State{
      serializer: Map.get(state, :serializer),
    }

    {:noreply, new_state}
  end
end
```

I'm not too familiar with this codebase, so maybe there are side effects that I'm missing. But if not, it would be a much more efficient solution than shutting down the store and instantiating a new one, and it would make the whole test setup much easier. We could just start the store in the test_helper, and only do a state reset in each `setup` call

Let me know what you think

**Comment by slashdotdash** [comment]
> Wouldn't it be possible to have a call on the InMemory GenServer that would just reset it's state to the initial one?

That's a possibility, but it's not quite so straightforward. Any subscriptions to the event store also need to be stopped (event handlers, read model projections, and process managers) since they also have state related to their last seen event. Stopping all active subscriptions will cause the subscribers to shutdown, but as they're linked processes this happens async. It might not have happened before the next test execution.

The simplest way to ensure a clean slate is by stopping and starting the application. This ensures all started processes in the application supervision tree are stopped. As you mentioned the downside of this approach is the overhead.

> Oh, and adding to the fact that we also need to stop it on_exit, isn't that a huge overhead for the setup/teardown of each test?

You only need to do this for _integration_ tests that require your app running; any unit tests can simply start/stop the individual `GenServer` under test or call the relevant function to test.

**Comment by slashdotdash** [comment]
> This would eliminate all the nuances that led to me posting this issue, and would make setup a lot easier to understand for everyone.

I completely agree that it's not an ideal scenario right now, so happy to hear suggestions to improve the situation.

I'm hopeful that the changes in #117 to support isolated Commanded instances to be independently started/stopped should help improve testing your own app.

**Comment by slashdotdash** [comment]
@naps62 Here's a reset callback for the in-memory event store that also stops any subscribers.

```elixir
@impl GenServer
def handle_call(:reset, _from, %State{} = state) do
  %State{
    persistent_subscriptions: persistent_subscriptions,
    serializer: serializer
  } = state

  for {_name, %Subscription{subscriber: subscriber}} <- persistent_subscriptions do
    Process.unlink(subscriber)
    Process.exit(subscriber, :shutdown)
  end

  {:reply, :ok, %State{serializer: serializer}}
end
```

Unfortunately this causes an issue as terminating event handlers and process managers (to clear their state) and having them restarted by their supervisor after each test stops working as the supervisor `max_restarts` and `max_seconds` are triggered. Instead, it may be preferable to have them implement a `reset` callback. I'm investigating how to solve this.

**Comment by slashdotdash** [comment]
@naps62 Some further feedback for you. 

I added `handle_info/2` callback functions to both event handlers and process managers. Instead of shutting down subscribers, resetting the in-memory event store sent a `:reset` message.

Running the test suite for Conduit (blogging example app using Commanded) the timings were as follows:

- Reset in-memory event store: 59.2s
- Use `Application.stop/1` and `Application.ensure_all_started/1`: 64.2 seconds

Is the minor performance improvement (~ 5%) worth adding the custom reset behaviour, and maintaining it?

**Comment by naps62** [comment]
well, if the difference is that small, then the performance argument is probably not relevant.

But even disregarding that, I would imagine that a way to reset the database state would make more sense than having to restart entire applications in between tests, conceptually speaking.
Of course, this would only apply if there are no side effects or dirty tricks that have to be employed, which from your earlier comment seems to not be the case.

I haven't had a chance to take a better look at this, and I'm not even working on our event commanded application at the moment, but tomorrow I'll pass on this discussion to the rest of the team (cc/ @ronaldofs

**Comment by revati** [comment]
I think test execution speed improvement isn't as important as ease of use. 
It would make much clearer how to test commanded applications. Wouldn't require much testing setup, just add `Commanded.EventStore.Adapters.InMemory.reset!()` in `setup` and that's it.

It probably is my incompetence, but starting and stopping application makes other [bugs](https://github.com/commanded/commanded/issues/177#issuecomment-417913839). It makes a steeper integration curve, as I'm trying to make my tests run green for a second day (not concentrating on business logic).

**Comment by slashdotdash** [comment]
I've made another attempt at the [in-memory event store](https://github.com/commanded/commanded/wiki/In-memory-event-store) page in the wiki. 

Start the in-memory event store in `test/test_helper.exs`:

```elixir
# test/test_helper.exs
alias Commanded.EventStore.Adapters.InMemory
alias Commanded.Serialization.JsonSerializer

{:ok, _pid} = InMemory.start_link(serializer: JsonSerializer)

ExUnit.start()
```

Use an `ExUnit.CaseTemplate` to reset the in-memory event store between after each test between stopping and starting the  application:

```elixir
# test/helpers/in_memory_event_store_case.ex
defmodule InMemoryEventStoreCase do
  use ExUnit.CaseTemplate

  alias Commanded.EventStore.Adapters.InMemory

  setup do
    on_exit(fn ->
      :ok = Application.stop(:my_app)

      InMemory.reset!()

      {:ok, _apps} = Application.ensure_all_started(:my_app)
    end)
  end
end
```

Then you can run tests using the standard `mix test` command.

**Comment by slashdotdash** [comment]
The `Commanded.EventStore` behaviour has been extended to include a `child_spec/0` function. This allows the configured event store to start its own process and/or supervisor. This should alleviate the problem of not having the in-memory event store running for tests.
