### ISSUE TITLE
Performance/Latency study

### ISSUE THREAD

**Issue by omidb** [commanded/commanded#154]
Hi,

I wanted to ask if you guys have done any study on the performance of Commanded. Do you have any numbers on the eventual consistency latency? How about the scalability of the system?

Thanks

**Comment by slashdotdash** [comment]
@omidb No, I've not measured the performance of Commanded outside of the benchmark suite for the Elixir [EventStore](https://github.com/commanded/eventstore#benchmarking-performance) which measures event append, read, and subscriptions. 

To asses the performance of Commanded for your own application would depend upon factors such as:

- Aggregates - How many active aggregates are there, do commands frequently target the same aggregate, or different instances, are they long-lived with frequent events, or short-lived with bursts of activity?
- Event handlers - How many are used, how quickly can they handle each interested event (e.g. you could offload their work to an external job queue, using the handlers just to enqueue the jobs).
- Hardware - Scale up vs. out and how many nodes are running, are they co-located within the same datacentre / switch / rack, how reliable is their network connection?

You'd likely need to build a prototype exhibiting the usage patterns and load you expect to support in production and asses the latency and performance yourself.

For scalability Commanded supports running on multiple nodes. You can run as either a distributed Erlang cluster or as multiple single instance nodes. [Commanded Swarm registry](https://github.com/commanded/commanded-swarm-registry) can be used to run on a cluster which allows aggregate and event handler processes to be distributed amongst all nodes using a consistent hashing algorithm. These processes will be redistributed when nodes join or leave the cluster. If you decide not to cluster the nodes then you can configure Commanded to use the Phoenix Redis pub/sub adapter for communication between nodes.
