### ISSUE TITLE
Can I make stream prefix empty?

### ISSUE THREAD

**Issue by drozzy** [commanded/commanded#157]
Right now if I make an identity prefix of an aggregate something, e.g. "car-":
```
identify Car, 
    by: :make,
    prefix: "car-"
```
My stream (in EventStore) will be "commanded-car-1".

Is there any way to get rid of "commanded-" part and just have "car-1"?

Just wanted to clarify why this is a problem: In EventStore everything before `-` is called a category, and so selecting `fromCategory("car")` will give everything including "car-1" etc.

But if the stream is called `commanded-car-1` then `fromCategory("commanded-car")` will not produce anything, because the category is "commanded" and not "commanded-car" in this case.

**Comment by drozzy** [comment]
The best I could achieve was:

```
config :commanded_extreme_adapter,
  serializer: Commanded.Serialization.JsonSerializer,
  stream_prefix: ""
```

And now all my streams look like this ;-)

`-Car-123`
`-Model-342`

**Comment by drozzy** [comment]
Ok, I figured out a workaround in EventStore itself. You can set a separator type and whether it comes first or last in the name of the stream.

It is done in the `$byCategory` projection. Here is how it should be set.

You also need to "reset" the projection if you already have data.

![screen shot 2018-03-26 at 12 33 26 am](https://user-images.githubusercontent.com/140710/37887073-912a23e2-308d-11e8-8198-0d668912116f.png)

**Comment by slashdotdash** [comment]
Closing as this issue relates to [Commanded Extreme adapter](https://github.com/commanded/commanded-extreme-adapter) (see [#12](https://github.com/commanded/commanded-extreme-adapter/issues/12)).
