### ISSUE TITLE
Is it possible to use environment variables in config?

### ISSUE THREAD

**Issue by Skoda091** [commanded/commanded#162]
I was trying to use environment variables for event store config, e.g:
```elixir
config :eventstore, EventStore.Storage,
  serializer: Commanded.Serialization.JsonSerializer,
  username: {:system, "ES_DB_USER", "postgres"},
  password: {:system, "ES_DB_PASSWORD", "postgres"},
  database: {:system, "ES_DB_NAME", "myapp_eventstore_test"}",
  hostname: "localhost",
  pool_size: 1
```
or with url
``` elixir
config :eventstore, EventStore.Storage,
  serializer: Commanded.Serialization.JsonSerializer,
  url: "postgres://postgres:postgres@localhost/myapp_eventstore_test",
  pool_size: 10
```
When defining config for ecto in order to pass variables during runtime we can use init callback from Repo module for that. Is there any way to use environment variables/ runtime config?

**Comment by slashdotdash** [comment]
@Skoda091 Yes, both of those config approaches are supported, but you need to use a two element tuple: `{:system, "ENV"}`

```elixir
config :eventstore, EventStore.Storage,
  serializer: Commanded.Serialization.JsonSerializer,
  username: {:system, "ES_DB_USER"},
  password: {:system, "ES_DB_PASSWORD"},
  database: {:system, "ES_DB_NAME"}",
  hostname: "localhost",
  pool_size: 1
```

**Comment by Skoda091** [comment]
@slashdotdash Thanks, for the answer. So it means that I cannot pass default option in case that env variable is not set?

**Comment by slashdotdash** [comment]
Sorry, just looked through the code again and it's only the `url` setting that can be set via environment variable (and there's no support for default values).

```elixir
config :eventstore, EventStore.Storage,
  serializer: Commanded.Serialization.JsonSerializer,
  url:  {:system, "ES_URL"}",
  pool_size: 10
```

Happy to accept a pull request if you'd like to add support for the other settings or three-tuple config with default fallback.

**Comment by Skoda091** [comment]
Thanks for investigation. I will try to create PR for that in my spare time :)
