### ISSUE TITLE
Allow event handlers to subscribe to individual streams

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#174]
By default, event handlers subscribe to all events appended to any stream. This approach causes issues when you have many events, but your handler is only interested in a subset of all events related to a single stream. 

It should be possible to subcribe a handler to a single stream, by its identity, using a `subscribe_to` option:

```elixir
defmodule ExampleHandler do
  use Commanded.Event.Handler, 
    name: __MODULE__,
    subscribe_to: "stream1234"

  def handle(%AnEvent{..}, metadata) do
    :ok
  end
end
```

In the above example, the configuration would guarantee only events appended to stream `stream1234` would be received and handled by the event handler.

**Comment by jfornoff** [comment]
https://github.com/commanded/commanded-extreme-adapter/pull/13 related
