### ISSUE TITLE
Event handler concurrency

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#184]
Allow event handlers to specify how many processes are started to allow handling events concurrently.

The behaviour is similar to Greg's Event Store which uses the [competing consumer](https://eventstore.org/docs/introduction/competing-consumers/) pattern. Increasing the concurrency means the event ordering guarantee is lost since events will be handled out-of-order. To alleviate this issue an optional partitioning function may be provided to ensure events are processed in order where necessary (e.g. per aggregate identity).

```elixir
defmodule ExampleHandler do
  use Commanded.Event.Handler, 
    name: "ExampleHandler", 
    concurrency: 10, 
    partition_by: fn _event, metadata -> metadata.stream_id end

  def handle(_event, _metadata) do
    :ok
  end
end
```

This feature depends upon Subscription concurrency ([#124](https://github.com/commanded/eventstore/issues/124)) to be implemented in the Elixir Event Store. Greg's Event Store already has support for concurrency.

**Comment by Aleksion** [comment]
This would be great - especially in situations where concurrency doesn't matter.

**Comment by Freyskeyd** [comment]
The `concurrency` parameter can be obscure.

Does it represent the maximum of events handled at the same time?
Does it represent the maximum event handler count for this kind of event handler?
Does it represent the number of event handler started by default?

The `partition_by` function is called to dispatch the event to the right event handler instance ? What's the default behaviour?

**Comment by slashdotdash** [comment]
- `concurrency` - How many event handler processes are started.
- `partition_by` - How to distribute events to running event handler processes. By default events will be distributed using a round-robbin strategy for even load.
