### ISSUE TITLE
Commanded.Aggregates.Aggregate module `execute` logic

### ISSUE THREAD

**Issue by bingoabs** [commanded/commanded#189]
This about the runtime logical.

I come cross it when read source code.
```
# Commanded.Aggregates.Aggregate
 def execute(aggregate_module, aggregate_uuid, %ExecutionContext{} = context, timeout \\ 5_000) do
    GenServer.call(
      via_name(aggregate_module, aggregate_uuid),
      {:execute_command, context},
      timeout
    )
  end
```

I print the value `via_name(aggregate_module, aggregate_uuid)`, kind of like:

```
  {:via, Registry, {Commanded.Registration.LocalRegistry, {Custom.Define.Aggregates, "author-id"}}}
```
But the `Custom.Define.Aggregates` no do `GenServer behaviour`. How this function can work?

Can you help to point my missing? Million thanks.

**Comment by slashdotdash** [comment]
@bingoabs The `GenServer` behaviour is defined in the [`Commanded.Aggregates.Aggregate` module](https://github.com/commanded/commanded/blob/266587f7786d27b390a355991cbb792944ac0885/lib/commanded/aggregates/aggregate.ex). This module handles the call/cast messages but delegates to your own aggregate module to execute commands and apply the resultant events to the state. It also handles fetching existing events from the event store, building the aggregate state, persisting new events to the event store, and storing snapshot data if state snapshotting has been configured.

**Comment by bingoabs** [comment]
@slashdotdash  Thanks for your detailed reply.
Hope I can totally understand this project and do something.
