### ISSUE TITLE
How to test process managers independently?

### ISSUE THREAD

**Issue by FrancisMurillo** [commanded/commanded#190]
Assuming I have a process manager that handles side-effects such as push notifications and socket channel broadcast, is there a way to make events to test the process manager independently? 

For now, I test the side-effects during my integration test which makes my tests more brittle and longer to execute. I'm thinking of creating a test router that wraps events into a command and just returns those events so that it can trigger the side-effects. I don't know if this is ideal or better means exist.

**Comment by slashdotdash** [comment]
You could use a mocking/stubbing library like [Mox](https://github.com/plataformatec/mox) to replace calls to stubbed modules implementing side effects for tests. This also allows you to verify expected calls were made during your tests if you wanted to. 

Define a behaviour for the module to mock:

```elixir
defmodule MyApp.Notifications do
  @callback send_push(String.t()) :: :ok | {:error, any}

  def send_push(message) do
    # Send actual push notification here ...
  end
end
```

In `test/test_helper.exs` define a mock for the behaviour:

```elixir
Mox.defmock(MyApp.NotificationsMock, for: MyApp.Notifications)
```

Configure the mock in `config/test.exs`:

```elixir
config :my_app, :notifications, MyApp.NotificationsMock
```

To use the notifications module in your process manager you would do:

```elixir
@notifications Application.get_env(:my_app, :notifications, MyApp.Notifications)

defp send_push(message) do
  @notifcations.send_push(message)
end
```

The above defaults to using the real notifications module (`MyApp.Notifications`) unless overridden by an app setting, which is done for the test environment only. 

In your unit test you define expectations and verify them, and then execute your process manager:

```elixir
use ExUnit.Case, async: true

import Mox

setup :set_mox_global
setup :verify_on_exit!

test "invokes add and mult" do
  MyApp.NotificationsMock
  |> expect(:send_push, fn message -> :ok end)

  # Trigger process manager by either dispatching a command 
  # or directly calling its `handle/2` function
end
```

**Comment by FrancisMurillo** [comment]
I had completely forgotten about mocks. :bulb: I installed `Mox` and used `expect`. Thanks for the tip.

I thought of calling the function, `handle/2`, directly as well but went with dispatching the event to check the wiring with it. I ran into two problems with dispatching the event:

1. Some aggregate state is invalid since the event requires a prior state.
2. Other process managers or projectors interfere with the test.

For the first one, is it possible to set the aggregate state as part of the fixture? If not, I think creating test routers to include only those relevant to the test is. 

For the other, is it possible to enable certain process managers during tests? If not then, directly calling the function instead might be better and asserting `interested/1` might be a good alternative.

**Comment by slashdotdash** [comment]
You might find it easier to unit test the process manager by directly calling its `interested?/1`, `handle/2` and `apply/2` functions. If you've mocked the side effects than you will be able to assert on the expected commands and/or state being mutated correctly. It also allows you to run the tests using ExUnit's `async: true` and they will be very fast.

**Comment by FrancisMurillo** [comment]
I think that's a good strategy too. I'll try that on my next iteration. Thanks for the prompt responses. Closing the issue.
