### ISSUE TITLE
Pass aggregate type name to the append_to_stream

### ISSUE THREAD

**Issue by drozzy** [commanded/commanded#195]
When `append_to_stream` function is called, it does not pass the aggregate type (e.g. "BankAccount"), but only passes the UUID:
https://github.com/commanded/commanded/blob/784bb619920c740d1ce422c6f4312df23d0c1c91/lib/commanded/aggregates/aggregate.ex#L488

here is the behaviour:
https://github.com/commanded/commanded/blob/master/lib/commanded/event_store/event_store.ex#L103

This makes it impossible to create category-specific streams in GetEventStore, where stream names follow the convention of:

- BankAccount-123
- BankAccount-234

This allows us to select all events from a category of "BankAccount", by simply doing the query for `$ce-BankAccount`.

If we had something like this, it would solve this issue:

```
append_to_stream(pending_events, aggregate_type, aggregate_uuid, expected_version, context) do
```

This would also allow us to get rid of the `prefix` in the extreme commanded adapter for eventstore.

**Comment by drozzy** [comment]
Also, just noticed that the spec declarations on lines 13 and 103 are the same:

https://github.com/commanded/commanded/blob/master/lib/commanded/event_store/event_store.ex#L19

https://github.com/commanded/commanded/blob/master/lib/commanded/event_store/event_store.ex#L103

**Comment by slashdotdash** [comment]
@drozzy You can use the [identity prefix feature in command routers](https://github.com/commanded/commanded/blob/master/guides/Commands.md#identity-prefix) to prepend an aggregate type to the stream identity used for persisting events.

```elixir
defmodule BankRouter do
  use Commanded.Commands.Router

  identify BankAccount,
    by: :account_number,
    prefix: "BankAccount-"

  dispatch OpenAccount, to: BankAccount
end
```

**Comment by slashdotdash** [comment]
The two spec declarations are identical, but one is a behaviour `@callback` and the other is a  `@spec` for a public function which implements the behaviour.

**Comment by drozzy** [comment]
Got it.
