### ISSUE TITLE
Process manager enforce `:start` and `:continue`

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#212]
Pull request #181 adds validation to ensure that when a process manager returns `{:continue, process_uuid}` it will guarantee the instance exists, otherwise the event is ignored. The same validation should be applied to `{:start, process_uuid}` to ensure the process does not yet exist.

Currently both `:start` and `:continue` behave as though they are "start or continue" where a process manager instance is resumed, regardless of whether it had been started or not. The above validation will affect the current behaviour and is potentially a breaking change to existing process managers. 

To address this I propose either:

### Start or continue

Adding a `{:start_or_continue, process_uuid}` option which replicates the current behaviour (a process is started or resumed regardless of previous state).

This will be a breaking change and existing process managers will need to be updated.

### "Strict mode"

Extend `:start` and continue to allow an optional strict mode enforcement: 

- `{:start, process_uuid, strict: true}` - validate process does not already exist.
- `{:continue, process_uuid, strict: true}` - validate process already exists.
- `{:start, process_uuid}` and `{:continue, process_uuid}` - the default behaviour without specifying strict mode will be as currently implemented.

Won't affect existing process managers, but allows consumers to opt-in to strict checking.

### Append `!`

Append `!` to start/continue to indicate strict mode following existing Elixir function naming style (per @fdbeirao's suggestion below):

- `{:start!, process_uuid}` - validate process does not already exist.
- `{:continue!, process_uuid}` - validate process already exists.
- `{:start, process_uuid}` and `{:continue, process_uuid}` - the default behaviour without specifying strict mode will be as currently implemented.

Won't affect existing process managers, but allows consumers to opt-in to strict checking.

--- 

Any thoughts or preferences on the above approaches, or suggestions for another options. This requires addressing before the next release can be published.

**Comment by fdbeirao** [comment]
An alternative to the strict mode syntax could be to use `:start!` and `:continue!`. I believe it is idiomatic in Elixir to use the `!` suffix as something that is "stricter" or can raise exceptions. Just my two cents for you to consider.

**Comment by Freyskeyd** [comment]
Hello,

@slashdotdash after reading this thread I was wondering, what if we are in strict mode on `:continue!` but the process manager isn't already started. Should we discard the event?

**Comment by slashdotdash** [comment]
@Freyskeyd We should call the process manager's `error/3` callback, passing the problematic event, and allow the consumer to decide how to handler the error (stop, retry, skip).
