### ISSUE TITLE
`{:error, :consistency_timeout}` in a cluster and swarm distribution strategies

### ISSUE THREAD

**Issue by leikind** [commanded/commanded#219]
I have a small Commanded app working perfectly well in a single node. I've modified it to run in a cluster with `commanded_swarm_registry` and `libcluster`, and here are some interesting findings:

* It works well with 3 nodes and  `config :swarm, distribution_strategy: Swarm.Distribution.StaticQuorumRing, static_quorum_size: 2`
* It works well with 2 nodes and  `config :swarm, distribution_strategy: Swarm.Distribution.Ring`.
* It does not work with 3 nodes and  `config :swarm, distribution_strategy: Swarm.Distribution.Ring `, :  `Router.dispatch(cmd, consistency: :strong)` returns `{:error, :consistency_timeout}`!

More info about the environment:

* `libcluster` 3.0.3, the strategy is `Cluster.Strategy.Epmd`
* `swarm` 3.3.1
* `commanded` 0.17.1, `event_store_adapter: Commanded.EventStore.Adapters.EventStore, registry: Commanded.Registration.SwarmRegistry, pubsub: [phoenix_pubsub: [adapter: Phoenix.PubSub.PG2, pool_size: 1]]`
* `commanded_swarm_registry` 0.2.0
* `commanded_eventstore_adapter` 0.4.0
* `commanded_ecto_projections` 0.7.1
* `eventstore` 0.15.1 `registry: :distributed`
* Elixir 1.7.3
* OTP release 21

What am I missing here? Why this consistency_timeout? I'd appreciate any hint.

**Comment by leikind** [comment]
I was just about to say that yes, I did add all this configuration, when I realized that I had added `registry: :distributed` to `config :eventstore, EventStore.Storage`, and not to `config :eventstore`

Thank you and sorry

**Comment by slashdotdash** [comment]
Not a problem, hope that fixes it for you.

**Comment by leikind** [comment]
it does
