### ISSUE TITLE
Accept list in the subscribe_to field

### ISSUE THREAD

**Issue by joaothallis** [commanded/commanded#221]
Have the ability to subcribe for multiple streams:
```elixir
defmodule ExampleHandler do
  use Commanded.Event.Handler, 
    name: __MODULE__,
    subscribe_to: ["stream1234", "stream4321"]

  def handle(%AnEvent{..}, metadata) do
    :ok
  end
end
``` 
In the above example, the configuration would guarantee only events appended to stream stream1234 e stream4321 will be received and handled by the event handler

**Comment by slashdotdash** [comment]
The Elixir EventStore and Greg's Event Store only support subscribing to individual streams. To implement this feature would require the Commanded event handle to create multiple subscriptions, one per stream. It would also need to ensure that event handling acknowledgements are sent to the correct subscription (based upon the event's stream identity to determine the subscription it originated from).
