### ISSUE TITLE
Question about Ecto.Adapters.SQL.Sandbox and truncating tables in a Commanded application 

### ISSUE THREAD

**Issue by leikind** [commanded/commanded#226]
I am just wondering why the blessed test configuration (https://github.com/commanded/commanded/wiki/Testing-your-application) uses truncating tables, and not `Ecto.Adapters.SQL.Sandbox`. Provided I run 

```
    :ok = Sandbox.checkout(Repo) 
    Sandbox.mode(Repo, {:shared, self()})
```
after the app restart in `Application.ensure_all_started(:my_app)` it should work just fine, I assume.

Also, is there a way **not** to restart the whole thing for each test?

```
 Application.ensure_all_started(:my_app)

    on_exit(fn ->
      :ok = Application.stop(:my_app)
      :ok = Application.stop(:commanded)
      :ok = Application.stop(:eventstore)
```

Thank you for the great library

**Comment by slashdotdash** [comment]
You can use Ecto’s sandbox to run your tests, albeit I found it was negligible in terms of test execution time compared to truncating tables.  Either approach will work. I’ve had no issues with truncating tables so just use what works for me!

Restarting the app, Commanded, and the EventStore between test executions guarantees that each test starts afresh with restarted process and state. This will become easier when you can define your own Commanded apps which would allow each test to start and use its own app.

**Comment by slashdotdash** [comment]
The [feature/in-memory-tests](https://github.com/slashdotdash/conduit/tree/feature/in-memory-tests) branch in the Conduit example repo uses the in-memory event store and Ecto Sandbox for tests. The storage module in the test support folder shows how I configured it to run.

**Comment by leikind** [comment]
Thank you!
