### ISSUE TITLE
Difference in keys between InMemory and EventStore adapters

### ISSUE THREAD

**Issue by vasspilka** [commanded/commanded#241]
When using the InMemory adapter for test the stored events have atom keys while the EvenStore adapter returns string keys. This causes some inconsistencies.

I would be expecting that when I retrieve an event it's identical no matter what adapter I use.

**Comment by slashdotdash** [comment]
By default the in-memory store _won’t_ serialize/deserialize events.

To enable serialization you must include the `serializer` option when starting the process:

```elixir
Commanded.EventStore.Adapters.InMemory.start_link(serializer: Commanded.Serialization.JsonSerializer)
```

Or define in config:

```elixir
# config/test.exs
config :commanded, Commanded.EventStore.Adapters.InMemory,
  serializer: Commanded.Serialization.JsonSerializer
```

**Comment by vasspilka** [comment]
I am closing the issue as the answer solves the problem
