### ISSUE TITLE
consistency timeout error when dispatching two strongly consistent commands through two different respective event handlers.

### ISSUE THREAD

**Issue by ThisisGurwinder** [commanded/commanded#248]
# Prerequisites
-  I am running the latest version
-  I checked the documentation and found no answer
-  I'm reporting the issue to the correct repository (for multi-repository projects)

I found one issue related to process-managers not able to make whole execution strongly consistent but not sure if it is related to this issue.
  possible related issue - "ProcessManager option `consistency: :strong` doesn't take effect #122" 

# Expected Behavior
I am listening for a strongly consistent event through two event handlers both dispatching strongly consistent commands. I was expecting the whole execution to behave in a strongly consistent manner.

# Current Behavior

I am getting the consistency timeout error.

# Failure Information (for bugs)

## Steps to Reproduce

1. Make an event with strong consistency.
2. Listen for that event in two different event handlers.
3. Dispatch strongly consistent commands from both of these handlers.

## Failure Logs
 14:37:31.217 [warn] Consistency timeout waiting for aggregate "user-4561bc72-1504-4816-b18e-59a7e3ed243e" at version 1

## Context
I think the event that I am dispatching with strong consistency is waiting for event handlers response but because process managers execution model is eventual by default it doesn't get the response as expected. If I make event handlers commands eventual consistent, it doesn't throw any error because this is I would guess how process managers model work.

I would like to know if both of these issues are related and work that we might do in upcoming releases related to issue #122 would also fix this.

**Comment by trbngr** [comment]
Any reason this is closed? This just bit me hard and I wasted nearly the whole of today coming to the same conclusions.
