### ISSUE TITLE
[Feature] EventHandler replays.

### ISSUE THREAD

**Issue by vasspilka** [commanded/commanded#253]
When I have a event handler I would like to be able to reset (or set to specific event_number) it's last_seen event and replay all the remaining events.

**Comment by norpan** [comment]
I use the eventstore.org and one way to replay all events for an event handler is to remove the subscription from the eventstore.org gui. Then the handler will resubscribe from 0.

**Comment by vasspilka** [comment]
You can do the same in the Postgres eventstore by setting the subscription `last_seen` number to 0.
I wanted to write a utility function for it.

**Comment by vasspilka** [comment]
Inclusion from Slack Tread

The event store subscriptions track the last seen event. To implement the above feature would require a change to the Elixir Event Store library (and also the in-memory and Extreme event store adapter).

The `Commanded.EventStore` behavior needs to be extended to support resetting subscriptions and the three existing adapters must be updated to implement the new behavior.

An event handler subscribed to the event store here: https://github.com/commanded/commanded/blob/ebaf9e195a60b37aa2d4afbe9ed8525a5d05905b/lib/commanded/event/handler.ex#L463

https://elixir-lang.slack.com/archives/C2REECQ1Z/p1559816405042000

**Comment by Freyskeyd** [comment]
@vasspilka A PR (#293) is open to be able to reset an EventHandler.

Feel free to comment if their is any question or improvement needed

**Comment by vasspilka** [comment]
@Freyskeyd Just took a look at the PR, looks good, pretty much what I had in mind :)

**Comment by slashdotdash** [comment]
Done in #293.
