### ISSUE TITLE
New jason deserializer (0.18) converts map keys inside events to atoms

### ISSUE THREAD

**Issue by norpan** [commanded/commanded#256]
Previously, when using the poison deserializer, it used
```
binary
|> Poison.decode!(as: type)
```
which converted the struct keys to atoms, but left the maps inside the keys alone.

Now it uses
```
binary
|> Jason.decode!(%{keys: :atoms})
|> to_struct(type)
```
which converts _all_ keys to atoms, not just the struct fields.

Since I have dynamic keys in my maps, this is not what I want. It seems like a regression.

Perhaps this should be changed to something like this?
```
binary
|> Jason.decode!()
|> to_struct(type)

defp to_struct(data, struct), do
    atom_keys_data =
        for {key,value} <- data, into: %{} do
            {String.to_atom(key), value}
        end
    struct(struct, atom_keys_data)
end
```

**Comment by slashdotdash** [comment]
If you’d like to alter the behavior I recommend you copy the existing reference JSON serializer and change it as required. This will allow you full control over how JSON is serialized.

**Comment by norpan** [comment]
Yes, I'm doing that, but isn't it still a regression?

**Comment by slashdotdash** [comment]
Migrating from Poison to Jason was marked as a breaking change for the v0.18.0 release.

**Comment by norpan** [comment]
Fair enough, perhaps this could be clarified that it's not only serialization but deserialization defaults that have changed.

**Comment by slashdotdash** [comment]
I’ll add a note to the CHANGELOG to warn about the affect to deserialization.

**Comment by norpan** [comment]
Thanks, yes, I think that’s good. It’s not just a compatibility issue though, having the code generate an arbitrary number of atoms is a problem, since the number of atoms is limited. So if you have event data with dynamic fields names you could easily reach the atom limit. Maybe this could also be noted.
