### ISSUE TITLE
Event upcasting

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#258]
Add support to Commanded for runtime event upcasting. 

Upcasting allows an event to be transformed before being passed to a consumer. You can use an upcaster to change the shape of an event (e.g. add a new field with a default, rename a field). Because the upcaster changes any historical event to the latest version, consumers (aggregates, event handlers, and process managers) only need to support the last version.

The upcaster could be implemented as an Elixir protocol, similar to the existing `Commanded.Serialization.JsonDecoder` protocol. It must have access to the raw event data and metadata, including event type.

**Comment by trbngr** [comment]
I've issued a PR of a spike of this feature.

An interesting feature of this is the ability to "adapt" an old event into a completely event type. This is a pretty powerful way of dealing with "legacy" event streams with newer code.

**Comment by trbngr** [comment]
This has been merged. Thanks Ben!!

**Comment by slashdotdash** [comment]
Done in #263.
