### ISSUE TITLE
dialyxir error with Commanded.Commands.Router

### ISSUE THREAD

**Issue by datafoo** [commanded/commanded#259]
When using a case statement on the result of the `dispatch` function of my router, I noticed dialyxir complaint about my code.

My router:
```elixir
defmodule MyApp.Router do
  use Commanded.Commands.Router
  …
end
```

My code (`lib/myapp/asset/asset.ex`):
```elixir
…
case MyApp.Router.dispatch(command) do
  {:error, error, reason} ->  # line 507
    {:error, error, reason}

  {:error, error} ->
    {:error, error}

  :ok ->
    successful_result
end
…
```
Dialyxir complain:
```
$ mix deps | grep dialyxir
* dialyxir 0.5.1 (Hex package) (mix)
  locked at 0.5.1 (dialyxir) b331b091
$ mix dialyzer
Checking PLT...
[:absinthe, :absinthe_plug, :asn1, :commanded, :commanded_ecto_projections,
 :commanded_eventstore_adapter, :compiler, :connection, :cowboy, :cowlib,
 :crypto, :db_connection, :decimal, :dialyxir, :dialyzer, :ecto, :ecto_sql,
 :eex, :elixir, :elixir_uuid, :eventstore, :exconstructor, :fsm, :gen_stage,
 :gettext, :hipe, :jason, :kernel, :logger, :logger_file_backend, :mime, :mix,
 :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :plug_cowboy, :plug_crypto,
 :postgrex, :public_key, :ranch, :runtime_tools, :ssl, :stdlib, :telemetry,
 :vex, :wx]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/home/datafoo/dev/myapp/_build/dev/dialyxir_erlang-21.2.5_elixir-1.8.1_deps-dev.plt',
  files_rec: ['/home/datafoo/dev/myapp/_build/dev/lib/myapp/ebin'],
  warnings: [:unknown]
]
done in 4m4.79s
…
lib/myapp/asset/asset.ex:507: The pattern {'error', _error@1, _reason@1} can never match the type 'ok' | {'error',_}
…
done (warnings were emitted)
```

I am using a validation middleware similar to [`Conduit.Support.Middleware.Validate`](https://github.com/slashdotdash/conduit/blob/f36fa57c61fd90803d19fb280675c29ddab25069/lib/conduit/support/middleware/validate.ex#L21) which I believe makes the `MyApp.Router.dispatch` return a tuple with the shape `{:error, :validation_failure, errors}`.

Looking at [`Commanded.Commands.Router`](https://github.com/commanded/commanded/blob/f03de7d294f8f3e5314c8ec3ce11368a807a5e95/lib/commanded/commands/router.ex#L143), it seems that `dispatch` should never returns a 3-element tuple:
```elixir
@callback dispatch(struct, keyword()) ::
              :ok | {:ok, non_neg_integer()} | {:ok, struct} | {:error, term}
```

I am confused, am I doing anything wrong by calling [`Commanded.Middleware.Pipeline.respond`](https://github.com/slashdotdash/conduit/blob/f36fa57c61fd90803d19fb280675c29ddab25069/lib/conduit/support/middleware/validate.ex#L21) with a 3-element tuple?

**Comment by slashdotdash** [comment]
I would recommend returning `{:error, {:validation_failure, errors}}` in the validate middleware so that the response is consistent with the function typespec. 

You can then pattern match on validation failures: 

```elixir
case MyApp.Router.dispatch(command) do
  :ok ->
    # success

  {:error, {:validation_failure, failures}} -> 
    # validation failure

  {:error, error} ->
    # catch-all error
end
```

The Conduit examples needs to be changed to follow this format.

**Comment by datafoo** [comment]
Thank you for this fast answer. It is clearer now.

**Comment by trbngr** [comment]
Sorry to pile on to this closed issue but, the spec doesn't account for `include_execution_result` either. I keep meaning to fix this but I just deal with it. ;)
