### ISSUE TITLE
Mock/stub random parts of events

### ISSUE THREAD

**Issue by Sephi-Chan** [commanded/commanded#260]
Hello,

I'm trying Commanded and my test app is a turn by turn strategy game (Risk like). When the game starts, I shuffle the players order.

``` elixir
def execute(%Game{game_id: game_id, players_order: players_order}, %StartDeployment{}) do
  if length(players_order) == 1 do
    {:error, :not_enough_players}
  else
    %DeploymentStarted{game_id: game_id, players_order: Enum.shuffle(players_order)}
  end
end

def apply(%Game{} = game, %DeploymentStarted{players_order: players_order}) do
  %{game | players_order: players_order, current_player_index: 0}
end
```

The problem is my tests can't be reliable when identifying the current_player.

``` elixir
test "player can't deploy a unit when he's not the current player" do
  :ok = Router.dispatch(%CreateGame{game_id: "42", creator_id: "Corwin", map: %{}})
  :ok = Router.dispatch(%JoinGame{game_id: "42", player_id: "Mandor"})
  :ok = Router.dispatch(%StartDeployment{game_id: "42"}) # here.
  {:error, :not_your_turn} = Router.dispatch(%DeployUnit{game_id: "42", player_id: "Mandor", territory_id: "Amber" })
end
```

How should I handle that?

Sending a `shuffled_players_order` in the argument of `StartDeployment` command would be possible, but is it the recommended approached? Is there any less *intrusive* way? Is it possible to stub/mock the created event?

Thanks!

**Comment by slashdotdash** [comment]
For testing aggregates I like to use an [`AggregateCase` ExUnit case template](https://gist.github.com/slashdotdash/097661df7e04ddfc11dbcb9a14d97124) which supports testing an aggregate module by providing a list of given events, a command to test, and either an expected list of events or an error. This test module expects you to provide a `build/2` function to construct commands and events in a `Factory` module. You can use the [ExMachina](https://hex.pm/packages/ex_machina) library to define these factory functions.
 
Using `AggregateCase` in the linked Gist would then allow you to write the following unit tests.

```elixir
defmodule GameTest do
  use AggregateCase, aggregate: Game
  
  @moduletag :unit

  describe "start game" do
    test "should be started" do
      assert_events(
        [
          {:game_created, game_id: "42", creator_id: "Corwin"},
          {:joined_game, game_id: "42", player_id: "Mandor"}
        ],
        {:start_deployment, game_id: "42"},
        [
          fn event ->
            {:deployment_started, game_id: "42", players_order: event.players_order}
          end
        ]
      )
    end

    test "should be started" do
      assert_error(
        [
          {:game_created, game_id: "42", creator_id: "Corwin"},
          {:joined_game, game_id: "42", player_id: "Mandor"},
          {:deployment_started, game_id: "42", players_order: ["Corwin", "Mandor"]}          
        ],
        {:deploy_unit, game_id: "42", player_id: "Mandor"},
        {:error, :not_your_turn}
      )
    end
  end
end
```

Notice that to test the "not your turn" error I'm explicitely creating a domain event with a known player order and then passing a command for the _wrong_ player to assert that an error is returned.

**Comment by slashdotdash** [comment]
Another approach is to pass in a module to shuffle the players as a field on the command:

```elixir
def execute(%Game{game_id: game_id, players_order: players_order} = game, %StartDeployment{} = command) do
  %Game{game_id: game_id, players_order: players_order} = game
  %StartDeployment{shuffler: shuffler} = command

  if length(players_order) == 1 do
    {:error, :not_enough_players}
  else
    %DeploymentStarted{game_id: game_id, players_order: shuffler.shuffle(players_order)}
  end
end
```

You can then use a mock/stub in tests to always return a known shuffle order (e.g. alphabetically).

**Comment by Sephi-Chan** [comment]
Thanks for the tips @slashdotdash ! It is good to know how others do things.
