### ISSUE TITLE
Aggregate state snapshots

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#27]
Implement rolling snapshots for aggregate state. This uses the memento pattern to serialize an aggregate's state. The serialized state is stored in the Event Store as snapshot data. 

Instead of loading every event for an aggregate when rebuilding its state you load the snapshot and then replay every event since it was created. 

As an example, assume the snapshot was taken after persisting an event for the aggregate at version 100. When the aggregate process is restarted we load and deserialize the snapshot data as the aggregate's state. Then we fetch and replay the aggregate's events from version 100.

This is a performance optimisation for aggregate's that have a long lifetime or raise a large number of events.

### Proposal

Configure snapshotting per aggregate within the app configuration. Define how frequently snapshots are taken (after every x events) and an optional snapshot version.

```elixir
# config/config.exs

config :commanded, ExampleAggregate
  snapshot_every: 100,
  snapshot_version: 1
```

Incrementing the snapshot version would ignore any previous snapshot taken at an earlier version during aggregate state rebuild. This allows changing the aggregate structure without requiring a snapshot data migration.

**Comment by drozzy** [comment]
I've done this on my own. It is not hard, just tricky.

Yes, you need to callbacks on the aggregate:

- `save_to_memento`
- `load_from_memento(memento)`

These would in the same place as the `apply` method is right now.

For snapshot stream, I use `AggName-snapshots-AggID`. So for aggregate `Foo` with id `123` it would be `Food-snapshots-123`.

The process that does "loading" from snapshots and events I call the _hydrator_, and here is there relevant piece of code (I'm sure your implementation is much more elegant, but you get the gist):

```
    def do_hydrate_from_snapshot(%Hydrator{snapshot_stream_id: id}=state) do
       state2 = case EvStore.read_events_backward(id, -1, 1) do
         {:error, :NoStream, _} -> state
         {:ok, %{events: events}} -> 
            [snapshot] = Adaptor.from_external(events)
            hydrate_from_snapshot(snapshot, state)
       end
       # Now start hydrating from events
       send self(), :hydrate_from_events
       {:noreply, state2}
    end

    def hydrate_from_snapshot(%Snapshot{memento: m, event_number: n}, %Hydrator{agg_mod: agg_mod, agg_pid: agg_pid}=state) do
       :ok = agg_mod.load_from_memento(agg_pid, m)
       %{state | last_event: n, last_snapshot_event: n}
    end
```

**Comment by slashdotdash** [comment]
@drozzy Thanks for the feedback.
