### ISSUE TITLE
Sending command from external system

### ISSUE THREAD

**Issue by ilgarm** [commanded/commanded#270]
Hello!

Could you point to the most correct way of sending commands into the backend ES system from outside, let's say CRUD service, assuming CRUD service is not part of the same Erlang cluster.

I currently can only think of three ways:
- using additional message pubsub system
- exposing REST endpoint in the backend system
- configure CRUD system with the same settings (relevant to the Router) as the ES system

In the last case I am not even sure if this will work if two systems are not part of the same Erlang cluster.

Thanks!

**Comment by slashdotdash** [comment]
You would need to provide an API for the other service to use. This could be a RESTful web service, GraphQL service, message queue, etc. The external request becomes a command which is dispatched in the event sourced system. 

You could use a Phoenix controller to dispatch the command ([here's an example from the Conduit sample repo](https://github.com/slashdotdash/conduit/blob/master/lib/conduit_web/controllers/article_controller.ex#L37). GraphQL mutations work well for dispatching commands in the resolver function where the command is constructed from the incoming params (which are already typecast).

**Comment by ilgarm** [comment]
@slashdotdash yes that what I was trying to avoid actually, bringing extra dependencies just to push a command, though I was expecting there is no clear way around this. Thanks for the confirmation and quick reply!
