### ISSUE TITLE
unsure about Commanded.Aggregate.Multi 

### ISSUE THREAD

**Issue by LostKobrakai** [commanded/commanded#276]
I'm wondering why `Commanded.Aggregate.Multi` is actually needed. Couldn't `execute/2` not just return a list of events without the additional complexity of building up a special struct?

**Comment by slashdotdash** [comment]
You can return just a list of events if you want. The Multi struct is useful when you want to mutate aggregate state after each command. Look at the example in the docs where a bank account deposit command returns a deposited event and then checks the state to see whether the account has gone overdrawn and optionally returns another event.

**Comment by LostKobrakai** [comment]
This makes sense. Seems I didn't pick up the changed aggregate part.
