### ISSUE TITLE
Commanded tool

### ISSUE THREAD

**Issue by zdenal** [commanded/commanded#278]
Hey Ben,
I am really sorry to reaching you via this issue. I didn't know where I could send you the idea ...

Currently I am working on one project using commanded. We were growing with code base so much that getting picture about flows is very hard. It gave me an idea if it is possible represent that flows in some graph with some features (source code of aggregates/handlers/... to get even better picture). Not sure if some tool is already existing, but I have spiked one.

It is not some silver bullet and it is really silly solution, but for our project it works. In project README I have also included the example when it was analysing https://github.com/slashdotdash/conduit.

**I wanted to ask you if you could add some `Tools` section to README of commanded where the community could contribute with some projects and let it be more visible for people who would like to contribute**. Here is the project I am talking about:
#### https://github.com/zdenal/commanded_events_map

Let me know what do you think about it .... looking forward for first feedbacks ;)

**Comment by slashdotdash** [comment]
Thanks @zdenal this looks neat. I've added a new [Tooling](https://github.com/commanded/commanded/wiki/Tooling) page to the Wiki and linked to it from the Commanded README.
