### ISSUE TITLE
Change identity depending on command

### ISSUE THREAD

**Issue by edgarjrg** [commanded/commanded#282]
Hi! I have 2 commands
```elixir
defmodule CreateProject3 do
  defstruct [:id, :prefix, :name]
end
```
and
```elixir
defmodule CreateFeature2 do
  defstruct [:project_id, :name]
end
```
Both go to the same aggregate, and my router looks like this:
```elixir
defmodule FeaturesRouter do
  use Commanded.Commands.Router
  
  identify Project3,
  by: :id,
  prefix: "project_v3_"
  
  dispatch CreateProject3, to: Project3, consistency: :strong
  dispatch CreateFeature2, to: Project3, identity: :project_id, consistency: :strong
end
```
But when i dispatch `CreateFeature2` i get `{:error, :invalid_aggregate_identity}`, i'm guessing the `identity` opts in the `dispatch` declaration is not about a Command field but the Aggregate, is a way to map the filed of the Command that is going to be compare against the Aggregate identity in the dispatch declaration? 

Thank you in advance :)

**Comment by trbngr** [comment]
I've run into the same issue. It seems that the `dispatch` registrations will not override the `identify` registration.

I simply ditched the `identify` and replicated it in my `dispatch`s

**Comment by slashdotdash** [comment]
@edgarjrg Using `identify` will override any `identity` setting for an individual command. You should either use the same field name for all commands for the same aggregate (e.g. always use `project_id`) or provide the `identity` setting for each command and remove `identify`.

It would seem more useful to be able to override the identity on a per-command basis as you tried to do (I'm not sure why I didn't implement it that way originally).

**Comment by edgarjrg** [comment]
@trbngr @slashdotdash thank you both for clarifying ☀️ i still have an issue though, if i ditch the `identify` i no longer can use the `prefix` that i use for versioning the `stream`, because the `identify` cannot be declared without the `by`, is there another way to specify the `stream` name?

**Comment by trbngr** [comment]
It's `identity-prefix` in the `dispatch` usage.

**Comment by edgarjrg** [comment]
Worked perfectly! i didn't find the `identity_prefix` in the docs but was right there in the command ops in the code :+1 everything works as expected with

```elixir
defmodule FeaturesRouter do
  use Commanded.Commands.Router

  dispatch CreateProject3, to: Project4, identity: :id, identity_prefix: "project_v4_", consistency: :strong
  dispatch CreateFeature2, to: Project4, identity: :project_id, identity_prefix: "project_v4_", consistency: :strong

end
```
thank you for your help :clap

**Comment by Freyskeyd** [comment]
@edgarjrg @slashdotdash 

Do we need to keep this issue open?
Is it resolved or do we need to implement a special case ?
