### ISSUE TITLE
Concurrent, Transactional End-To-End Tests

### ISSUE THREAD

**Issue by xtagon** [commanded/commanded#283]
Hi,

This is sort of an "out there" idea, and likely not easy to accomplish, but I am hoping to get your thoughts.

DockYard published a blog post describing how to add "Concurrent, Transactional End-To-End Tests" to a Phoenix application using the Ember framework for the frontend. It's a really neat thing to accomplish. The tests can run on the Ember side as acceptance tests, proxy to the Phoenix backend running in test mode, and each instance of a test can check out its own Ecto connection which is wrapped in a transaction. Tests can run concurrently without leaking shared state.

https://dockyard.com/blog/2017/11/15/how-to-add-concurrent-transactional-end-to-end-tests-in-a-phoenix-powered-ember-app

I recently started setting this up on one of my apps as a test/learning experience, and quickly ran into a problem: It's not compatible with Commanded (or event sourcing in general, at least out of the box), because it only takes care of the Ecto repo.

Do you think it would be possible to get a variant of this technique working with Commanded in the mix?

I see two main challenges:

1. It may be possible to use phoenix_ecto as normal to take care of the read models/projections, but only if you're using Ecto for that and not necessarily other types of projections/handlers. I tried getting this far, but it isn't working yet, and I believe it has something to do with which processes are accessing the Ecto model, which I haven't tracked down yet (I'm also using Absinthe as well as Commanded, so there's quite a bit of misdirection here).

2. Even if it was working for the read models, the event store itself would be another story. The GetEventStore adapter, I'm not familiar with at all, so someone else will have to weigh in on that possibility. The Postgres EventStore is what I'm currently using, but it doesn't use Ecto, so I'm not sure how it could be made to work with this method, but perhaps it's possible. Another idea is to design a variant of the in-memory adapter which can have separate "transactions" per connection, perhaps some sort of fully persistent data structure that can handle more than one timeline of the state of the event store and roll each one back after each test.

Thoughts?

**Comment by slashdotdash** [comment]
@xtagon To reliably support concurrent tests I think it will be necessary to support running concurrent Commanded apps (proposed in #117). This would allow an environment per test process to be started which would also need its own isolated event store (e.g. using the in-memory adapter). That would allow the tests to be completely isolated from one another. Unfortunately that's a significant change and has not yet been started.

**Comment by xtagon** [comment]
That makes sense. If each test instance had its own isolated event store, the only other part would be wiring it up to the Ecto read models to roll back their transactions during teardown.

**Comment by slashdotdash** [comment]
See pull request #324.
