### ISSUE TITLE
Commanded tool #2

### ISSUE THREAD

**Issue by zdenal** [commanded/commanded#288]
Hey Ben,
I sorry again to reaching you via issue.

I am working on another commanded tool: https://github.com/zdenal/commanded_debugger

This tool should allow people to track commands/events in debug application w/ simple UI. More in README in repository.

I would like to ask if you could also include this into tool section https://github.com/commanded/commanded/wiki/Tooling to get some feedback from community and maybe somebody would also willing to help me with it to properly finish it.

Let me know what do you think about it .... looking forward for first feedbacks ;)

**Comment by slashdotdash** [comment]
I've added it to the [Tooling](https://github.com/commanded/commanded/wiki/Tooling) page in the Wiki. Looks like another useful tool.
