### ISSUE TITLE
Do I need to use an event store?

### ISSUE THREAD

**Issue by jfrense** [commanded/commanded#289]
I was reading the documentation and it wasn't clear to me if it was possible to use commanded without implementing an event store.

I would like to take a gradual approach and implement the CQRS pattern only first and then maybe in the future implement event sourcing.

Is this possible ?

**Comment by slashdotdash** [comment]
Commanded only supports storing aggregate state using event sourcing (and optionally state snapshots as a performance optimisation). You cannot use any other persistence mechanism to store aggregate state.
