### ISSUE TITLE
Regression introduced in the logger

### ISSUE THREAD

**Issue by datafoo** [commanded/commanded#294]
I introduced a regression in the logger in `Commanded.Middleware.Logger.delta/1`:
https://github.com/commanded/commanded/commit/deb15cf688a312fae27279f628294a1af696f8f7#diff-858f93ba6e33b9c3a7db0521dc3c8b45

The logger displays negative durations which does not make sense, my apologies.

**Comment by Freyskeyd** [comment]
Hello,

Thank's for reporting the issue. Feel free to open a Pull Request at any time 😄

**Comment by datafoo** [comment]
Of course, I am working on it.
