### ISSUE TITLE
Third Party Libs

### ISSUE THREAD

**Issue by trbngr** [commanded/commanded#297]
I think it's cool that someone has been creating tools for Commanded. So I thought I'd share with the community some macros that have helped us a lot.

This is a library of some helper macros around creating command and events.

https://github.com/trbngr/commanded_messaging

Enjoy.

**Comment by slashdotdash** [comment]
Thanks Chris, this looks useful. I've added the library to the [Tooling page](https://github.com/commanded/commanded/wiki/Tooling) on the Wiki.
