### ISSUE TITLE
Projectors long delay on new deployments

### ISSUE THREAD

**Issue by voshawn** [commanded/commanded#300]
When I deploy a new version of my app, it is taking about 10 minutes or more for my projector to update when a new event occurs. This is leading to `consistency_timeout` errors and outdated read models for an unreasonably long time. 

However, after about 10 minutes things seem to be work fine. I've spent a few days trying to figure out what is causing this and how I can fix it. Here are some of the hypotheses I've tested:

- Is it because of the `consistency: :strong` settings? The issue still occurs when remove it from my dispatchers and projectors. 
- Is it because the app is taking a long time trying to rebuild the aggregate state and that is somehow blocking the projectors? When I set the aggregate lifespans to `:stop` after every command, event, and error this still occurs. 
- Is it because of a multi-node (no cluster) deployment without setting up Redis? On my staging server, I only have one VM and this issue still occurs. 

I am running an elixir 1.9 (umbrella app) with: 
```
{:commanded, "~> 0.19"},
{:eventstore, "~> 0.17"},
{:commanded_eventstore_adapter, "~> 0.6"},
{:commanded_ecto_projections, "~> 0.8"}
```
I am deploying on Google Cloud Instances with Cloud SQL (postgres) for the database. For deployment, I'm basically just doing mix release and starting the build on VMs behind a load balancer. The eventstore and the read models are in two different databases in the same instance.

**Comment by trbngr** [comment]
Hi Shawn,

We run into almost the same issue on AWS ECS. We deploy a new instance and the load balancer keeps both around until it determines the new instance is healthy.

Here's my simple hypothesis:

- New instance comes to life and subscribes all handlers to event store

- A command is dispatched with strong consistency to one of the instances

- The other instance's subscription picks up the event and finishes

- The original instance will never get an ACK because the event was handled on the other instance.

- Load balancer determines that all is good and removes old instance

- Stuff starts working as normal

This is indeed scary to experience in production. The only way I can think of to mitigate it, would be to cluster both instances using libcluster/swarm or the like. Which is where I'm heading next.

**Comment by slashdotdash** [comment]
Dispatching a command with strong consistency works as follows:

1. Command is dispatched (using `consistency: :strong`) via a router.
2. Aggregate executes the dispatched command and returns one or more events.
3. Events are persisted to the event store and the updated aggregate version and events are returned to the command dispatch process.
4. The dispatch process will wait until all of the handlers configured to use `:strong` consistency have acknowledged receipt of the new event(s) (in [`Commanded.Middleware.ConsistencyGuarantee`](https://github.com/commanded/commanded/blob/master/lib/commanded/middleware/consistency_guarantee.ex#L36)) by waiting until they've processed the event for the expected aggregate version.
5. The event(s) are published to the event handlers by the event store whenever they're ready to handle them. 
6. Each event handler acknowledges the event after successful processing. 
7. Once all of the event handlers have processed the event(s) created from the command dispatch then the dispatch call completes. If this takes too long then an `{:error, :consistency_timeout}` is returned instead.

Commanded uses the configured registry for pub/sub notifications of each event acknowledgement. By default this uses a local Elixir `Registry` module, which can only run on a single node. If you have multiple nodes running then you *must* use the [Phoenix pubsub registry](https://github.com/commanded/commanded/blob/master/lib/commanded/pubsub/phoenix_pubsub.ex) with Redis (non-distributed Erlang) or PG2 (distributed Erlang) as described in the [Deployment guide](https://hexdocs.pm/commanded/deployment.html).

**Comment by slashdotdash** [comment]
@trbngr Are you using Redis (or distribured Erlang with PG2) for the Commanded registry? The main app that I'm working on is hosted on AWS ECS and has four instances running. We use a single Redis instance for the pubsub and rolling deployments work seamlessly with that setup.

**Comment by slashdotdash** [comment]
@voshawn & @trbngr If the above suggestion helps you out let me know and I'll add more detail to the documentation to clarify the behaviour.

**Comment by voshawn** [comment]
Hi @slashdotdash and @trbngr,

Thanks for the thorough reply. It was helpful to understand, but I think this may be caused by something else. I just tried setting up Redis and it did not solve the issue.  This makes sense because in my original post, I mentioned I tried to deploy without any `:strong` consistency.

But I think we're close. Here's some additional information that may help:

I inspected the logs and this is what happens:
1.  When the app is started in a new instance, I get this message: `Subscription "MyProjector"@"$all" attempting to connect subscriber #PID<x.xxxx.x>` 
2. Then every minute I get: `Subscription "MyProjector"@"$all" subscribe to stream`. 
3. This happens multiple times until eventually, I get:
 ````
Subscription "MyProjector"@"$all" catching-up
MyProjector has successfully subscribed to event store
````
4. After we subscribe successfully for the first time, if I start and stop the app on the VM (or stop the app and then redeploy), the subscription is successful on the first try.  However, if I keep the app running and then do a rolling restart the issue occurs. 

So the question is: What could be preventing Projectors from successfully subscribing in this case?  

Is it possible that the way the app gets shut down in a rolling restart/replace somehow messes with a future subscription? 

BTW: This is my Redis setup. I had to add `pool_size`: 
```
{:phoenix_pubsub_redis, "~> 2.1.0"},

config :commanded,
  registry: :local,
  pubsub: [
    phoenix_pubsub: [
      adapter: Phoenix.PubSub.Redis,
      host: "x.x.x.x",
      port: 6379,
      pool_size: 5,
      node_name: "localhost",
    ]
  ]
```

**Comment by slashdotdash** [comment]
Seeing the "Subscription <name>@<stream> subscribe to stream" log message repeated every minute for each handler is expected if you have multiple nodes running. 

The reason for this is that when an event handler starts it attempts to connect to its subscription. If the same handler is already running and connected on another node then the subscription will fail and be retried after a minute. Handlers which haven't been able to subscribe will keep retrying so that if the already running and connected handler process crashes (or the node hosting it is stopped) it can takeover the subscription from wherever it got to.

Subscriptions are locked using Postgres' advisory locks. Any locks are released when the database connection is disconnected. This should mean that during a rolling deploy the old node is stopped, releasing its subscription locks, and the running node(s) should be able to acquire the locks when they next check (once per minute).

You could try reducing the retry interval below the 1 minute default to see whether that helps:

```elixir
# config/config.exs
config :eventstore, subscription_retry_interval: 10_000  # 10 seconds
```

**Comment by slashdotdash** [comment]
Looking at your Phoenix pubsub config, are you setting different `node_name` for each node in production (instead of "localhost")?

I use an environment variable which is set to a unique value per node: `node_name: System.get_env("NODE")`

**Comment by voshawn** [comment]
Ah no I'm not using a unique value. I wasn't too sure the significance of node_name. Can I just

**Comment by trbngr** [comment]
> @trbngr Are you using Redis (or distribured Erlang with PG2) for the Commanded registry?
> 
> The main app that I'm working on using Commanded is hosted on AWS ECS and has four instances running. We don't use distributed Erlang (the nodes are not connected to each other) so we use a single Redis instance for the registry pubsub. With that setup rolling deployments work seamlessly as the acknowledgements are broadcast to all nodes via Redis using strong dispatch consistency.

No I'm not and I feel stupid now 😁

**Comment by voshawn** [comment]
Okay so this is still an issue for me, but I think it is now out of scope for commanded. After making my node names unique, I still had the issue so I did some more digging. Here's what's going on:

- From what you said about advisory locks I decided to go into psql to look at the active connections and locks during my deployment process. 
- It turns out that when google cloud stops / shuts down an instance, the database connections do not close until approximately 8 minutes later.  
- This means that the connection and the locks are still in place after my new instances are up; therefore creating a delay in the new projectors being able to subscribe. 

I'm going to put in a support ticket with GCP and see if they can help me figure this out since I can't seem to find anything related to this problem online. My temporary solution could be to run `pg_terminate_backend(pid)` on the process that has the lock after deploying. 

Thanks for the help debugging this! All of this information has been super helpful broadly. Let me know if you want to close the issue or if you have some other ideas I should explore.

**Comment by voshawn** [comment]
I talked to google cloud support. They said the issue was likely due to some keepalive connection. They recommended that create a shutdown script that runs when instances are restarted or shut down. In this script I added `pkill beam.smp` and `pkill cloud_sql_proxy` and this solved my issue. Now the database connections and locks are removed when my instances shut down, which allows my new projectors to subscribe successfully. 

These were the key insights that helped me resolve this: 

> If you have multiple nodes running during your deployment, but are only using the default :local registry, then the above steps won't work because the event handler acknowleging events on one node won't be published to a second node. Command dispatch will likely always timeout in that scenario because the dispatch is blocked waiting for an acknowledgement it will never receive. You need to use Redis (or distributed Erlang) for multi-node deployment, even if you only have two nodes running for a brief window during deployment.


> Subscriptions are locked using Postgres' advisory locks and all acquired locks are released when the database connection is disconnected. This should mean that during a rolling deploy the old node is stopped, releasing its subscription locks, and the running node(s) should be able to acquire the locks when they next check (within the next minute).

Thanks for all the help!

**Comment by slashdotdash** [comment]
Glad to hear you have a workaround in place to alleviate this issue. Good detective work in tracking down the root cause. It’s worth me adding this info somewhere to the Commanded docs to help anyone else who bumps into the same problem. I’m also going to look into what’s issuing the long keep alive for the database connection.
