### ISSUE TITLE
Long running command processing

### ISSUE THREAD

**Issue by ilgarm** [commanded/commanded#305]
Hello,

In a documentation it is specified that command processing is happening in a dispatch process, and has a default timeout of 5 seconds. I can increase this timeout, but my understanding is that it might delay other commands dispatching. Is this correct?

My question also is if this is the right way to process long running task. So, let's say I need to import something from the remote source, and the task might take minutes/hours/etc, and I am issuing a command to initiate that. What should be the proper way to handle that? Can I do that in a command handler? Or should I issue an event and then handle this in an event processor or process manager?

The only place in the docs regarding long running tasks I have found in a section of event processors/process managers.

Thanks!

**Comment by slashdotdash** [comment]
>  I can increase this timeout, but my understanding is that it might delay other commands dispatching. Is this correct?

Yes, any further commands dispatch to the aggregate instance will be blocked behind the long running command.

> Can I do that in a command handler? Or should I issue an event and then handle this in an event processor or process manager?

I would usually delegate the long running task to a background job queue using an event handler. This could be done by dispatching a command to start the task (e.g. `StartImport`), creating a domain event (e.g. `ImportStartRequested`), and using an event handler to enqueue the background job. On completion the task could report back its status by dispatching another command (e.g. `NotifyImportComplete`).

The reason for delegating the actual work to a background job queue (which could be just a `Task` or spawned Elixir process) is that it doesn't block the event handler from processing subsequent events.

**Comment by ilgarm** [comment]
I initially was thinking to avoid having an extra command and event just to start the import, but you are right, it might be helpful for auditing purposes as well.

What if background task fails and will not have a chance to send back status update command. Will usage of process manager help in the context of retries? I am fine having a dedicated process manager per import per source, and it will also help me serialize import operations per remote source, probably. What is your opinion on using process manager for long running operation?

Thanks!

**Comment by slashdotdash** [comment]
> What is your opinion on using process manager for long running operation?

A process manager in Commanded is also blocking so would suffer the same issue as only being able to run one import at a time, regardless of how many instances are started. 

Ideally each instance of the process manager would be able to run concurrently so it wouldn't matter if they were individually blocking. This issued has been raised in "Event sourced process managers" (#137).

**Comment by ilgarm** [comment]
OK I see. Probably, then till the new version is released a background task is the only viable option.
Thank you!
