### ISSUE TITLE
Multiple commanded applications, same store?

### ISSUE THREAD

**Issue by naps62** [commanded/commanded#349]
I'm not sure if this is an intended use case? I was upgrading to commanded 1.0, but it seems I misunderstood the possibilities here

I created 2 different commanded applications in my umbrella app, both of which pointing to the same event storage. My thinking here was that this would allow me to keep each handler supervised under its own context, but still be able to receive events from the global store.

But it seems what happens is that the pubsub mechanism only notifies subscriptions registered within the same application.
So, did I misunderstand this? Am I suposed to have a single application per store?

**Comment by slashdotdash** [comment]
@naps62 Using the same event store for multiple Commanded applications wasn't an intended use case. It was designed so that each application used its own event store, to provide isolation. 

I'd have to investigate whether sharing a single event store between apps could be made to work.

**Comment by naps62** [comment]
thanks for the clarification :+1:
