### ISSUE TITLE
Passing restart strategy for handlers and process manager.

### ISSUE THREAD

**Issue by vasspilka** [commanded/commanded#361]
Is there currently a way to pass a restart strategy to a handler / process manager? 
Maybe something like

```
use Commanded.Events.Handler, 
    name: "Handler",
    application: Project.Application,
    restart: :transient 
```

**Comment by larskluge** [comment]
I do not believe this is currently supported, but it can be accomplish by overwriting `child_spec`. e.g. in this hacky way (not recommended): 

```elixir
  defoverridable child_spec: 1
  def child_spec(init) do
    %{
      id: __MODULE__,
      restart: :temporary, # :transient,
      start: {__MODULE__, :start_link, [init]},
      type: :worker
    }
  end
```

**Comment by vasspilka** [comment]
I am closing this as I think in general it's a bad idea to do so.
Initially, the idea was to avoid retrying after x amount of time to block too many notifications. 
But I think instead its best to handle that in the error context instead of relying on a dead process not sending any :P
