### ISSUE TITLE
Request of wiki update: add bonfire as an example app

### ISSUE THREAD

**Issue by qhwa** [commanded/commanded#367]
Hi @slashdotdash ,

I've created an application running on top of Commanded, Phoenix, and LiveView.
https://github.com/qhwa/bonfire

It's open-source and has a running website in production [here](https://bonfire.ooo).

Would you mind putting my app on [the wiki page of example applications](https://github.com/commanded/commanded/wiki/Built-with-Commanded)?

Any feedback is also welcome and appreciated.

**Comment by slashdotdash** [comment]
Nice work @qhwa, the website looks great. I added a few DDD-inspired books to my profile (https://bonfire.ooo/slashdotdash). I think this is the first example I've seen of integrating Commanded with LiveView, it works well.

I've added it to the "Built with Commanded" page in the Wiki.
