### ISSUE TITLE
Using changesets for command validations?

### ISSUE THREAD

**Issue by naps62** [commanded/commanded#370]
My current project is using Ecto Changesets to build and validate commands. When first getting in, I was trying to improve the current flow, for a couple of reasons. Here's the current pattern being used:

```elixir
defmodule Command do
  def new(params) do
    cast(%__MODULE__{}, data, @fields)
    |> validate_required(@fields)
    |> apply_action(:insert)
  end
end

# and somewhere else:
with {:ok, cmd} <- Command.new(params),
         :ok <- Router.dispatch(cmd) do
  # ...
end
```

I have two problems with this:
1. It's leaving command validation as a responsibility to the outside code. An inexperienced developer can easily use `%Command{}` instead of calling `Command.new`, and validations would be bypassed completely
2. It makes the code a bit more verbose in every single place where a command is dispatched

My ideal scenario would be doing something like this:

```elixir
defmodule Command do
  def new(params) do
    cast(%__MODULE__{}, data, @fields)
    |> validate_required(@fields)
    
    # no apply_action/1 here, meaning a changeset is returned, instead of a Command struct
  end
end

# and somewhere else:
with {:ok, changeset} <- Command.new(params),
         :ok <- Router.dispatch(changeset) do
  # ...
  else
    {:error, %Changeset{}} -> # probably a validation error in the cmd
end
```

However, this approach doesn't work, because the intuitive way to do is (adding a Middleware to the router) only works when the final struct is received.
The `dispatch` call needs to know where to route the command, before even calling the middleware

So I was wondering if there is some pattern that could be introduced here (either as a PR to commanded, or a recommendation for our own side) to implement this.

My original idea was along these lines:

```elixir
defmodule Middleware do
  def before_dispatch(%Pipeline{command: changeset} = pipeline) do
    case apply_action(changeset, :insert) do
      {:ok, cmd} -> %Pipeline{pipeline | command: cmd}
      {:error, changest} ->
        pipeline
        |> respond({:error, %{reason: :invalid_command, changeset: changeset})
        |> halt()
     end
  end
end
```

**Comment by zdenal** [comment]
Olaaa @naps62 nice to speak with you after longer time!!!

Not sure it can solve completely the issue you are pointing, but maybe this could be interesting for you: https://github.com/trbngr/commanded_messaging
Mainly parts as:
- https://github.com/trbngr/commanded_messaging#validation
- https://github.com/trbngr/commanded_messaging#command-dispatch-validation

I hope you are well and enjoying live.

**Comment by naps62** [comment]
Hi @zdenal!

Thanks for the link. I've sinced move to use ExConstructor + Vex, which seems to do a pretty similar job as that package.
So this is no longer an issue for me, although I'd still be curious if there's a way to integrate these more seamlessly?

**Comment by slashdotdash** [comment]
@naps62 Commanded uses the command struct for routing, that's a requirement. You may be able to include the Ecto changeset as a field in the command and use the middleware approach to apply validation to it and populate the command fields from it when valid. A convenience macro or shared functions could hide the boilerplate for doing this for each command struct.

**Comment by sardaukar** [comment]
@naps62 here's an example of command validation using Skooma https://blog.nootch.net/post/event-sourcing-with-elixir-part-6/

**Comment by naps62** [comment]
Thank you all :)

slashdotdash already answered my question, so I think this can be closed
