### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by davydog187** [commanded/commanded#374]
Hello @slashdotdash !

Thank you as always for all of your great work on commanded! We have been eagerly awaiting the next release of commanded for many of the pending changes, especially the stack trace improvements and Phoenix 1.5 support.

Is commanded ready for its next release, or is there something holding it up? Anything I can lend a hand to help with?

**Comment by slashdotdash** [comment]
I've published [v1.1.0 to Hex](https://hex.pm/packages/commanded/1.1.0).

**Comment by davydog187** [comment]
Thanks Ben!
