### ISSUE TITLE
[question] Migrating legacy data to event store

### ISSUE THREAD

**Issue by sineed** [commanded/commanded#378]
Recently I decided to start using ES and CQRS via commanded on existing project already having some data. I started to think about how can I migrate my data to events. I started with a simple scenario for entities with only 1 `created` event. I wanted to get the excepted result of working app using events but still using to my existing tables only as a read model (or projection).

The first idea is that my future projector temporarily stops updating data for the `created` event until I run task that migrates my existing data. So here is the simplified script:

```elixir
stream_prefix = "blog-post-"
posts = MyApp.Repo.all(MyApp.Blog.Post)

Enum.each(posts, fn(post) ->
  causation_id = UUID.uuid4()
  correlation_id = UUID.uuid4()

  evt = %MyApp.Blog.PostCreatedEvent{
    post_uuid: post.id,
    title: post.title
  }

  data = [
    %Commanded.EventStore.EventData{
      causation_id: causation_id,
      correlation_id: correlation_id,
      event_type: Commanded.EventStore.TypeProvider.to_string(evt),
      data: evt,
      metadata: %{},
    },
    #...additional events for more complex entities
  ]


  :ok = Commanded.EventStore.append_to_stream(MyApp.EventApp, stream_prefix <> evt.post_uuid, 0, data)
end) 
```

I wonder to know is this approach is acceptable for `commanded` and `eventstore` in terms of the architecture. Are there some limitations of migrating data such way to the event store?

It will be also great to hear other approaches to this problem.

**Comment by slashdotdash** [comment]
Mathias Verraes has written an article [outlining a few strategies for migrating events from another system](https://verraes.net/2019/06/eventsourcing-patterns-migration-events-ghost-context/). 

What you're doing would work ok. You could also consider using a special `PostImported` or `PostMigrated` event which signifies this was imported or migrated from an external source. It might be useful to have this separate from `PostCreated` events as the imported data could be much richer.

**Comment by sineed** [comment]
thanks for the article and your advice, it helped to decide how it can be done entirely
