### ISSUE TITLE
Catch exceptions in Process Manager apply/2

### ISSUE THREAD

**Issue by marpo60** [commanded/commanded#379]
Hi,

I have a PM that has defined the `error/3` callback but when throwing an exception during the `apply/2` command does not trigger the `errors/3` callback

Looking at the code I figured it out that we are not rescuing on apply/2

Handle processing:
https://github.com/commanded/commanded/blob/4a6df4a3fc3e318805574ca9cab5cef0a83617e3/lib/commanded/process_managers/process_manager_instance.ex#L235-L243

Apply processing:
https://github.com/commanded/commanded/blob/4a6df4a3fc3e318805574ca9cab5cef0a83617e3/lib/commanded/process_managers/process_manager_instance.ex#L323

The `interested/3` is also catching exceptions:
https://github.com/commanded/commanded/blob/4a6df4a3fc3e318805574ca9cab5cef0a83617e3/lib/commanded/process_managers/process_router.ex#L292-L398

If you think this is something that we should fix I can work on a PR.

**Comment by slashdotdash** [comment]
Yes, it would be worth catching exceptions from the `apply/2` function. A pull request would be gladly accepted!
