### ISSUE TITLE
Distributed Environment

### ISSUE THREAD

**Issue by delmendo** [commanded/commanded#382]
I have multiple nodes running the application. I have a managed postgres instance with a database for the commanded eventstore and the readstore.  I think I have all the distributed configurations setup right (I'm using libcluster auto configuration for EventStore  and PhoenixPubSubRedis for the application). As I perform operations it seems like everything is good, but I'm a little gun shy after my problem with projection.

Is there a way in production to test to confirm that the nodes are all happy and working as expected?   Also you have mentioned that you use the Redis way of sharing instead of Swarm - is there a trade off there I should be aware of?  I'm still very new at the Elixir ecosystem so I'm trying to understand when I should do it the elixir/erlang way and when I should do it the way I would with other systems.

**Comment by slashdotdash** [comment]
One approach you could use is to monitor subscriptions to the EventStore to verify that they are up-to-date. This could be done using the [`telemetry`](https://hex.pm/packages/telemetry) and [`telemetry_poller`](https://hex.pm/packages/telemetry_poller) libraries where you query the database to see how many pending events there are to process per subscription. If any subscription's pending event count is continually growing then you likely have an issue.

The following SQL query can be used to determine how up-to-date each subscription is:

```SQL
SELECT
  subscriptions.subscription_name,
  subscriptions.last_seen,
  streams.stream_version - subscriptions.last_seen as pending_events
FROM subscriptions
INNER JOIN streams on streams.stream_uuid = subscriptions.stream_uuid;
```

With the telemetry polling in place you can set up an alert if any pending events count increases beyond an acceptable level. This will ensure that distributed event handlers and process managers are running successfully.
