### ISSUE TITLE
Not compatible with Phoenix 1.5.0

### ISSUE THREAD

**Issue by pcarvsilva** [commanded/commanded#388]
Failed to use "phoenix_pubsub" (version 2.0.0) because
  commanded (version 1.0.1) requires ~> 1.1
  phoenix (versions 1.5.0 to 1.5.3) requires ~> 2.0
  mix.exs specifies ~> 2.0

**Comment by slashdotdash** [comment]
Commanded [v1.1.0](https://github.com/commanded/commanded/blob/master/CHANGELOG.md#v110) includes support for Phoenix PubSub v2.0 ([#365](https://github.com/commanded/commanded/pull/365)). Upgrading should resolve the dependency conflict and allow you to use Phoenix v1.5.x.
