### ISSUE TITLE
Allow event handlers and process managers to implement an `init/1` callback function

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#392]
Similar to the [`Commanded.Application.init/1`](https://hexdocs.pm/commanded/Commanded.Application.html#c:init/1) callback function which allows an application to be dynamically configured at runtime. Allow the implementation of an `init/1` callback function for `Commanded.Event.Handler` and `Commanded.ProcessManagers.ProcessManager` modules which would be called with the merged compile-time and runtime config and must return the (optionally) updated config.

#### Example

```elixir
defmodule ExampleHandler do
  use Commanded.Event.Handler, application: ExampleApp
 
  def init(config)
    {tenant, config} = Keyword.pop!(config, :tenant)
    
    # Set a tenant-specific name
    config = Keyword.put(config, :name, "ExampleHandler." <> tenant)
 
    {:ok, config}
  end
end  
```

Usage:

```elixir
{:ok, _pid} = ExampleHandler.start_link(tenant: "tenant1")
```

Or supervised as: `{ExampleHandler, tenant: "tenant1"}`

**Comment by larskluge** [comment]
Great, thank you @slashdotdash ! Seems to work well, but a minor thing: one still has to provide a `:name` even when it's set via `init/1`. 

e.g.

```elixir
  use Commanded.Projections.Ecto,
    application: App,
    repo: Repo,
    name: "not used, overwritten by init/1"
```

**Comment by slashdotdash** [comment]
> Great, thank you @slashdotdash ! Seems to work well, but a minor thing: one still has to provide a `:name` even when it's set via `init/1`.

Good spot.  This is due to Commanded Ecto projections expecting the name to be provided at compile-time. I’ve created a separate issue to fix it (https://github.com/commanded/commanded-ecto-projections/issues/31).
