### ISSUE TITLE
Allow the command identity to be provided during command dispatch

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#394]
Currently the command identity is [assigned during command dispatch](https://github.com/commanded/commanded/blob/56e116504946c58eeb8701e9ed8b53f553e97404/lib/commanded/commands/router.ex#L556) as `UUID.uuid4()`. It would be useful to be able to provide the identity during command dispatch.

#### Example

```elixir
MyApp.dispatch(command, command_uuid: custom_identity)
```

**Comment by lex-mala** [comment]
Has anyone started this yet? I'm willing to take it if not.

**Comment by slashdotdash** [comment]
> Has anyone started this yet? I'm willing to take it if not.

Not yet, it's free to take on.
