### ISSUE TITLE
How to pass some metadata to the Aggregates execute/2 commands?

### ISSUE THREAD

**Issue by cjuniet** [commanded/commanded#403]
Hi, I'd like to pass some metadata to my aggregates' `execute/2` functions (in particular the `correlation_id` and the `aggregate_uuid`) so I can send logs during commands, in the context of the aggregates own processes, with the same metadata as in the router process.

It seems that it's not possible because `Commanded.Aggregates.Aggregate.execute_command/2`  passes only the `state` and the `command`, but not the full `ExecutionContext`, with `Kernel.apply(handler, function, [aggregate_state, command])`.

Since I have not found any way to put the `correlation_id` in every logs, I've pushed the PR https://github.com/commanded/commanded/pull/402 to pass the execution context before each command execution with an optional `before_execute/2` callback, called just before the `execute/2` callback, with the user-defined aggregate state and the current execution context.

This is particularly useful to do some setup in the context of the aggregate process (e.g. set the aggregate's own logger's metadata). For instance:
```
defmodule MyApp.Router do
...
  dispatch([MyApp.Commands.Account.Create, ...],
    to: Account,
    identity: :iban,
    before_execute: :before_execute)
...
end

defmodule MyApp.Aggregates.Account do
  require Logger

  alias Commanded.Aggregates.ExecutionContext

  def before_execute(%Account{} = state, %ExecutionContext{} = context) do
    %ExecutionContext{correlation_id: correlation_id, command: command} = context
    %Account{iban: iban} = state

    Logger.metadata(aggregate_id: iban)
    Logger.metadata(correlation_id: correlation_id)
    Logger.metadata(command_id: command.id)
    Logger.metadata(command_name: inspect(command.__struct__))
    Logger.metadata(command_data: Jason.encode!(Map.from_struct(command)))
  end

  def execute(state, %MyApp.Commands.Account.Create{} = command) do
    Logger.info("...")
    ...
  end
end
```

**Comment by slashdotdash** [comment]
Done in #402.
