### ISSUE TITLE
Allow a process manager to stop after dispatching a command

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#441]
A process manager instance can only be stopped by returning `:stop` from the `interested?/1` callback function. This doesn't allow you to decide when to stop the instance based upon its state and/or a recently dispatched command. It would be useful to support stopping an instance from either the `handle/2` function or as a new callback function, such as `after_command/1`.

### Add an `after_command/1` callback function

The return value from the callback function would control when the process manager instance is terminated. The callback function would only be called after the command is successfully dispatched. A dispatch error would call the existing `error/3` function.

#### Example

```elixir
defmodule ExampleProcessManager do
  use Commanded.ProcessManagers.ProcessManager,
    application: ExampleApp,
    name: "ExampleProcessManager"

  def handle(%ExampleProcessManager{}, %AnEvent{}) do
    [%SomeCommand{}]
  end

  def after_command(%ExampleProcessManager{}, %SomeCommand{}) do
    :stop
  end
end
```

This is similar to the existing `Commanded.Aggregates.AggregateLifespan` behaviour which contains an `after_command/1` function.

### Allow a process manager `handle/2` function to stop an instance

Allow a process manager's `handle/2` callback function to return a tuple in the format `{command, :stop}` to dispatch one or more commands and then stop the process manager instance.

#### Example

```elixir
defmodule ExampleProcessManager do
  use Commanded.ProcessManagers.ProcessManager,
    application: ExampleApp,
    name: "ExampleProcessManager"

  def handle(%ExampleProcessManager{}, %AnEvent{}) do
    command = %SomeCommand{}

    {command, :stop}
  end
end
```

**Comment by philipgiuliani** [comment]
Are there any plans to implement the second version (`{command(s), :stop}`). The problem is that I emit multiple commands multiple times, but in a special `handle` clause I need to stop it after emitting the commands. The only workaround I can think of right now, is to create a custom command which I will emit, just to stop the process manager afterwards.
