### ISSUE TITLE
Dispatch commands in event handler atomically

### ISSUE THREAD

**Issue by MMore** [commanded/commanded#446]
Hello,

is there a way to dispatch multiple commands in an event handler atomically? I am using the Postgres Eventstore, so I was wondering how to do that?

The commands are affecting the same aggregate, so the consistency boundary of the aggregate applies.

Thanks a lot!

**Comment by drteeth** [comment]
Do you mean that you want both commands to succeed or fail as a unit? I don’t think that’s possible. You would probably make a command that expresses the combined intents and then handle that. You can emit the same events as the two separate commands.

**Comment by MMore** [comment]
Indeed I was able to transform those multiple commands in multiple events in the mean time. Thanks you.

**Comment by MMore** [comment]
Hello again,

so the design changed a little bit. I would like to "fan out" an event: based on one event (aggregate A), create multiple other events (each event affects one instance of the same aggregate B) to handle them separately. 
But when I create all those events by a command I'd like to ensure that all or no events are created. Any idea how to handle that?

**Comment by vasspilka** [comment]
I would suggest creating a command that includes all the information you need for both events. Then create multyple events with that command

**Comment by vasspilka** [comment]
Would that solve your issue? In general event handlers are not the best to dispatch commands, we have the process manager abstruction for that. What exactly are you trying to do? The issue is a bit confusing

**Comment by MMore** [comment]
Yes, I built it like that, but it feels more like a workaround. 
As I said, after an event occured I need to change multiple instances of another aggregate, means executing multiple commands. I've built a layer in between to execute another command which creates multiple events so that I can execute an command in an event handler. But yeah, feels like a workaround.

**Comment by drteeth** [comment]
If you're crossing aggregate boundaries then you don't have any atomic way of ensuring they all succeed or fail. This is kind of by definition: the aggregates are the consistency boundaries.

* You can use a Process Manager and fan-out the commands, then consider the implications of rolling back if some child aggregate fails. This is what process managers and sagas are meant for.  It's not nearly as simple/clean as an all-or-nothing transaction, but it works across machines and is generally what I've read in the es/cqrs literature.

* You can re-think your aggregate boundaries. Let the tension you're feeling here guide you, something is not right. Maybe a larger aggregate is needed here to maintain consistency.

* If the child commands are truly, truly follow-on effects from handling the initial command, and require no additional validation, then perhaps you skip the command handler/aggregate and write the events directly to the event store. Be sure you understand the implications if you take this option. 

If you need more concrete advice, give us more detail on your problem and we can go from there. Consider joining #commanded or #eventsourcing channels on the elixir slack channel to talk it through. https://elixir-slackin.herokuapp.com/

**Comment by MMore** [comment]
Thanks a lot @drteeth!
