### ISSUE TITLE
Pass metadata/ExecutionContext to aggregate execute/2 callback.

### ISSUE THREAD

**Issue by revati** [commanded/commanded#465]
# Proposal:
Ability to pass `Commanded.Aggregates.ExecutionContext` or just metadata (for simplicity sake further referred just as metadata) to the `execute` callback. In many places in commanded lib based on callback arity metadata is passed or not. Similarly it might be done for `execute` callback.

Some command executions might need metadata and some might not, so there might be both `execute/2` and `execute/3` callbacks. Dynamically detecting for which command to pass metadata probably will be headache.

Simpler solution might be to configure it in router:

```
defmodule MyApp.Router do
...
  dispatch [MyApp.Commands.Account.Create, ...],
    to: Account,
    identity: :iban,
    with_context: :metadata | :execution_context
...
end
```

# Use-cases

## Pass data from metadata to event

command: `CreatePost`
event `PostCreated` (yes i know this is CRUDish, this is for example sake)

All commands dispatched passes current user id as metadata. To know who to blame in case of something. And for precise auditlogs. For long time created post indeed was owned by current user, so there weren't :owner_id field neither for command, nor event. 

But once we introduce "login as" functionality, one person can do stuff on behalf of other. So in metadata we pass actual user id and user id on which behalf stuff is done. But based on different conditions, sometimes current user is owner and sometimes authorised as user is owner. It seems that if further future there might be cases when third (organisation owner) will be post owner as well. 

Said logic calculation should happen in aggregate and be passed to event, so all listeners can just blindly accept event data, not to calculate it again. I could pass all those user ids as command fields as well, but it would clutter command with metadata.

## Generic event triggers

Trigger additional event if caller ip (which is in metadata) has changed. I could pass it as command value, but i would need to do so for all aggregate commands and this field is irrelevant from each specific command point of view. But is required logic for broader aggregate behaviour.

# Drawbacks

Aggregate is dependant on implicit data that might turn out not to be present. For me this seems as rare case, as usually (from my experience) metadata structure wise are identical for all command dispatches (`%{current_user_id: ..., ip: ..., tenant: ..., ...}`).

Either case this would give more freedom for developers (at least for me :D) to choose implicit over explicit, to reduce repetition if necessary.

As mentioned above all use cases sort of can be achieved by sending all those metadata via command as well. Easy hack: all commands (or at least necessary ones) have metadata field which has exactly the same metadata info as passed as well

```
Application.dispatch(%CreatePost{..., metadata: metadata}, metadata: metadata)
```

# Current state of library

Currently there is some ability to access `Commanded.Aggregates.ExecutionContext` in aggregate via `before_execute` (#403), but it can only be used to deny command execution or do some side effects. There is no way to use `before_execute` response to change aggregate state or append new events to stream. 

I think my proposal has overlap with `before_execute` but has broader applications and can do more. I would even argue to replace `before_execute` with my proposed solution, but that would mean backwards compatibility issues.

**Comment by slashdotdash** [comment]
The intended behaviour for command handling, such as the aggregate's `execute/2` function, is that any information needed to make a decision is included in the command. If the user id is needed to decide what events to produce then it should be included in the command. 

For a generic approach you could define a router middleware which copies the metadata onto the command:

```elixir
defmodule IncludeMetadataMiddleware do
  @behaviour Commanded.Middleware

  alias Commanded.Middleware.Pipeline
  import Pipeline

  def before_dispatch(%Pipeline{command: command} = pipeline) do
    %Pipeline{command: command, metadata: metadata} = pipeline

    enriched_command = Map.put(command, :metadata, metadata)
  
    %Pipeline{pipeline | command: enriched_command}
  end

  def after_dispatch(%Pipeline{} = pipeline), do: pipeline
  def after_failure(%Pipeline{} = pipeline), do:  pipeline
end
```

**Comment by slashdotdash** [comment]
In the scenario where the data wasn't available in the command/event but was in the metadata and you later decide that it is required in the event then you can use the [upcasting feature](https://hexdocs.pm/commanded/Commanded.Event.Upcaster.html):

```elixir
defimpl Commanded.Event.Upcaster, for: AnEvent do
  def upcast(%AnEvent{} = event, metadata) do
    %AnEvent{event | user_id: Map.get(metadata, "user_id)}
  end
end
```
