### ISSUE TITLE
config/0 not being used and @config being used instead which causes application to start with default or config configured during compile time

### ISSUE THREAD

**Issue by xshadowlegendx** [commanded/commanded#476]
hello I am producing elixir release using `distillery` and make use of its `Distillery.Releases.Config.Providers.Elixir` to configure `commanded` in production but the runtime config not being used and instead it uses the default config which I had inside `config/config.exs` for development, as I look into the `Commanded.Application` module, I think I saw that `config/0` was supposed to be used instead of `@config` as it also return default config if no runtime config exists, but `@config` was used instead inside the `start_link/1` https://github.com/commanded/commanded/blob/6cbd898ba2a3f95e5575519fd625e362ea80ca63/lib/application.ex#L198

**Comment by slashdotdash** [comment]
For runtime configuration you can either use the [`Commanded.Application.init/1`](https://hexdocs.pm/commanded/Commanded.Application.html#c:init/1) callback function to configure the application.

**Comment by xshadowlegendx** [comment]
@slashdotdash  hello thanks for reply, let me try the init callback then

**Comment by xshadowlegendx** [comment]
hello @slashdotdash  it is working as expected now, thanks
