### ISSUE TITLE
General design philosophy question: sending email from process manager

### ISSUE THREAD

**Issue by DrewEaster** [commanded/commanded#488]
Commanded is a fabulous project and a great advert for DDD in general. I have a design philosophy question regarding process managers.

Imagine a certain state change within a process manager that would mean the desire to send a notification email. From my understanding, the general pattern for process managers is event => aggregate command. This makes a lot of sense from a DDD perspective. But, what would I do in this email scenario? Can a process manager trigger other behaviour other than just sending commands to aggregates? Even if it can, should it? If a process manager can't - or shouldn't - do that, then what would the "right" approach be for this?

Using a DDD mindset, would it be better to formalise the concept of the notification as an Aggregate? i.e. have the process manager create an instance of some notification aggregate, and then use a general stateless event handler (not a process manager) to trigger the sending of an email on seeing a `PendingNotificationCreated` event. The handler could send a follow up command to the aggregate to let it know the email has actually been sent to the external mail system.

I've very interested to understand the philosophies for this sort of stuff, especially from those who are advanced enough as DDD practitioners to create something as excellent as Commanded!

**Comment by DrewEaster** [comment]
Thanks @drteeth. Great advice. I'll head over the slack channel for any followups.

**Comment by yordis** [comment]
@DrewEaster is this still an issue?

@slashdotdash do you think it would be a good idea to enable the Discussions to ask these types of questions so people don't create issues for it?

**Comment by slashdotdash** [comment]
I've enabled [discussions](https://github.com/commanded/commanded/discussions) for the Commanded repo.
