### ISSUE TITLE
update FAQ regarding scheduling

### ISSUE THREAD

**Issue by dvic** [commanded/commanded#490]
https://github.com/commanded/commanded/wiki/FAQ#how-do-i-schedule-commands-for-later-dispatch

The FAQ refers [commanded-scheduler](https://github.com/commanded/commanded-scheduler) but it seems this project is deprecated based on commanded/commanded-scheduler#13: 

> I don't have any current plans to upgrade it. Using Commanded v1.x would allow a separate Commanded application and event store to be used for scheduling which would make it more self-contained. That is a worthwhile upgrade.

Maybe the FAQ should be updated to reflect this latest advice?

**Comment by slashdotdash** [comment]
I've updated the FAQ to remove the reference to the outdated Commanded scheduler project.
