### ISSUE TITLE
warning: redefining module Commanded.Serialization.JsonDecoder.Any

### ISSUE THREAD

**Issue by yordis** [commanded/commanded#504]
## Context

Hey peeps, we are getting the following error:

```
warning: redefining module Commanded.Serialization.JsonDecoder.Any
```

Due to doing the following:

```elixir
defimpl Commanded.Serialization.JsonDecoder, for: Any do
  def decode(%module_name{} = data) do
    cond do
      function_exported?(module_name, :__schema__, 1) ->
        data
        |> Ecto.Changeset.cast(Map.from_struct(data), module_name.__schema__(:fields))
        |> Ecto.Changeset.apply_changes()

      true ->
        data
    end
  end

  def decode(data) do
    data
  end
end
```

We intend to cast the events into `embedded_schema` Ecto schemas to type cast values into the appropriate structured data primarily.

It feels that the default implementation of Protocols should be at the application-specific code, but inconvenient.

Ideally, I shouldn't have to create an entire different Serializable.

**Comment by slashdotdash** [comment]
Not implementing the `Commanded.Serialization.JsonDecoder` for `Any` would mean another manual task required to setup Commanded for most consumers of the library. My preference is to reduce this type of additional configuration as much as possible.

**Comment by yordis** [comment]
> Not implementing the Commanded.Serialization.JsonDecoder for Any would mean another manual task required to setup Commanded for most consumers of the library. My preference is to reduce this type of additional configuration as much as possible.

Hard to disagree with that one for sure!
