### ISSUE TITLE
Individual stream events handling

### ISSUE THREAD

**Issue by maslowalex** [commanded/commanded#555]
Please help me to understand how to handle events from individual streams. I'm been using Commanded for more than a year now, but still it's really hard for me to understand how to do this simple thing.

I got this in my router:

```elixir
  identify(Aggregates.Identity, by: :hashed_identity, prefix: "identity-")

  dispatch(Commands.Login, to: Aggregates.Identity)
```

Then in EventHandler:

```elixir
  use Commanded.Event.Handler,
    application: MyApp.App,
    name: __MODULE__,
    start_from: :origin,
    subscribe_to: "identity"
```

Upon dispatching of the command I can see the `identity-` prefix in the `stream_id` field, like: `identity-zRcB77sjpxcD8Hh9pWjq4_g5Pf3KU5g_pPxqRzcxsLQ=`

The aforementioned event handler does not receiving the event.

I was trying to append the `stream_id` (`stream_uuid` what is difference btw, it's so confusing...) to the command itself when I dispatching it, but that doesn't help either:

```elixir
App.dispatch(stream_id: "identity")
```

**Comment by vheathen** [comment]
@maslowalex there is no `identity-` stream by default. This prefix will be added to the aggregate identifier after events are published and used as its stream name. In this exact case this individual stream name becomes `identity-zRcB77sjpxcD8Hh9pWjq4_g5Pf3KU5g_pPxqRzcxsLQ=`. And event store will contain a lot of such streams, one per aggregate identity. The same for all aggregates you have.

The only "common" stream by default is `$all`. When you add a new event handler without `subscribe_to` it will subscribe to the `$all` stream by default.

But if you need to have something like context streams ("accounts" or "orders" or whatever you'd like) you can create an event handler which will subscribe to `$all` stream and then link some events to the specific stream (or multiple). I believe this is not optimal and reduces performance, and, if necessary, events should be linked to the context streams when they appended to the aggregate's stream, but it is what we have now.

More on linking events [in the recipes](https://github.com/commanded/recipes/issues/16).

**Comment by maslowalex** [comment]
Thank you for answer @vheathen !
