### ISSUE TITLE
Correlation and causation ids

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#70]
[Greg Young explains](https://groups.google.com/forum/#!msg/dddcqrs/qGYC6qZEqOI/LhQup9v7EwAJ) correlation and causation ids succinctly as:

> Every message has 3 ids, MessageId, CorrelationId, CausationId. 
> 
> When you are responding to a message (either a command or an event) you copy the CorrelationId of the message you are responding to to your message. The CausationId of your message is the MessageId of the message you are responding to. 

Currently, Commanded does not set causation id, and correlation id is set as a generated UUID  when appending events. It should follow the approach outlined by Greg above.

**Comment by fdbeirao** [comment]
Quick and maybe unrelated question. Do you see the `correlationId` as being semantically the same as a *saga identifier*, from [Hector Garcia-Molina's paper "sagas"](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.93.7258&rep=rep1&type=pdf):

> The begin-saga command can return a saga identifier to the program. This identifier can then be passed to the system on subsequent calls made by the saga.

Or am I mixing up two concepts here?

**Comment by slashdotdash** [comment]
@fdbeirao No, I don't think so. 

In Commanded you would use a process manager to implement a saga. So I would say the identity returned from the process manager's `interested?/1` function is the identity for the process manager (aka saga). 

In the example below it is the `transfer_uuid` that uniquely identifies a single instance of the transfer money process manager:

```elixir
defmodule TransferMoneyProcessManager do
  use Commanded.ProcessManagers.ProcessManager,
    name: "transfer_money_process_manager",
    router: BankRouter

  def interested?(%MoneyTransferRequested{transfer_uuid: transfer_uuid}), do: {:start, transfer_uuid}
  def interested?(%MoneyWithdrawn{transfer_uuid: transfer_uuid}), do: {:continue, transfer_uuid}
  def interested?(%MoneyDeposited{transfer_uuid: transfer_uuid}), do: {:stop, transfer_uuid}
  def interested?(_event), do: false

  # ...
end
```
